### ISSUE TITLE
Sluice recipe / Container version enabled

### ISSUE THREAD

**Issue by recklectic** [Beyond-Reality/Beyond-Reality-Divergence#10]
makes bibliocraft disc rack

**Comment by Dominance** [comment]
Seems there is more issues with the sluice currently. There is two types one being a container sluice and one being a non container sluice. The non container version is meant to be enabled which requires real world interaction and not GUI based.

**Comment by Dominance** [comment]
Fixed in 1.0.9 soon to be released
