### ISSUE TITLE
Request: Reactorcraft

### ISSUE THREAD

**Issue by Leftorius** [Beyond-Reality/Beyond-Reality-Divergence#102]
I see that you will add Rotarycraft to it and I would love to see some better "reactor mods" than big reactors in this pack and so I though, why just dont ask if there are plans to add it in the future? :D

**Comment by Dominance** [comment]
No plans currently. I love the mod as much as the next person and add it to my own custom version of classic Beyond Reality. With Divergence how ever there is already massive amounts going on in the ore gen department. ReactorCraft just has way to many ores that populate chunks that have very very few uses. For instance there is a 4 ores that make a grand total of 2 items together.

**Comment by Leftorius** [comment]
Yeah you're right :/ too bad :I
