### ISSUE TITLE
Raw ores + IE crusher

### ISSUE THREAD

**Issue by thunderpanter** [Beyond-Reality/Beyond-Reality-Divergence#103]
Is there a reason that you cant process raw ores in the immersive engineering crusher?, or is it intended that the pressure packager must be used to compress the ores beforehand, by which the crusher becomes redundant due to the reliance on the pressure packager.

**Comment by Dominance** [comment]
Yes atm this is the only method available. I am awaiting bdew to help me out to add something to compacter. One done you will be able to use the compacter to speed up the process and bypass the pressure packager. No ETA
