### ISSUE TITLE
Visual quest issue in tech

### ISSUE THREAD

**Issue by Dominance** [Beyond-Reality/Beyond-Reality-Divergence#105]
http://i.imgur.com/Mk79BKW.png Putting this here to show everyone I know about this issue. And after two + hours I cannot seem to find a solution if someone has one please do share :)

**Comment by thunderpanter** [comment]
Pretend its a pop-up book

**Comment by airbreather** [comment]
Try this: https://www.dropbox.com/s/kj4qurao4wx1n2d/quests-fixed.hqm?dl=0

Please test it to make sure that the only thing that changed was the location of that one quest.  If something else changed, let me know and I'll try to undo it.

**Comment by Dominance** [comment]
Ok seems as if the only thing that changed is the location of the quest. How ever LOL http://i.imgur.com/8Tr1ROr.png Its almost there! Ether way it looks a heck of a lot better now than it did. Thanks a ton for the help I am for ever in your debt. If you can manage to get it towards the top that would be amazing!

**Comment by airbreather** [comment]
Hmm, I thought the issue you were having was that you couldn't edit the quest because it was off the page.  So I just took the 10 or so minutes to find the quest in the file and plop it back onto the page so that you could edit it using the normal tools.  But a quick test suggests that you can in fact edit things that are off the page, so I guess that wasn't it.

What are you looking for help with, exactly?

**Comment by Dominance** [comment]
I have not tried to move the build craft quest after the fix myself. If that is so you may of fixed it already. But yeah basicly to get the build craft quest to move up towards the top of the book is all. The normal editor no matter how many times I attempted to move it would always revert back to off the page location. Prior to your fix

**Comment by Dominance** [comment]
I have attempted to move the quest in game. After you do on reload it puts it back to the orignal spot on the first screen shot http://i.imgur.com/Mk79BKW.png

**Comment by airbreather** [comment]
Are you able to make other changes in the quest log, perhaps to other quests, and have them persist appropriately? If not, you have a different problem that's unrelated to this particular quest.  Check that the quests.hqm file is writable, that there's no error in the log file, etc.

**Comment by Dominance** [comment]
Yeah I can change the text add task remove task pretty much anything. The only thing that does not seem to save is that one quest location. Even though before moving it http://i.imgur.com/xXz1z8A.png  MD5 3D8EE548353E0BBF6C488C77517372FB  after moving http://i.imgur.com/zfEgg4v.png and saving MD5 B78BEB60B88D30C95353575F0204D79B So it is defiantly saving and changing the file structure. Note that reloading the game puts it here http://i.imgur.com/fWMf02d.png and the MD5 stays the same at B78BEB60B88D30C95353575F0204D79B

**Comment by Dominance** [comment]
Fixed \o/
