### ISSUE TITLE
Crash after mining a few ore

### ISSUE THREAD

**Issue by Hazdrubal** [Beyond-Reality/Beyond-Reality-Divergence#110]
After mining a few blocks of nickle ore, I crash.

http://pastebin.com/J0NDydCB

**Comment by Dominance** [comment]
This is one of thoughts no real way to tell why it crashed logs. the only way I would have a chance to figure it out is if I had both the client FML and server FML log both corresponding to the exact time this happened.

**Comment by Githubaccountlol** [comment]
Happening to me too. Happens again every time I try to connect.

**Comment by helkarakse** [comment]
Server side log: http://pastebin.com/5pEFqSeN, Server side FML Log: http://pastebin.com/sxT324CL for the above comment.

**Comment by Githubaccountlol** [comment]
I don't have the FML for the actual first occurrence anymore, but this is from the most recent connection.  Same attempt as the one helk posted.

http://pastebin.com/XDmj1Xh8

**Comment by Dominance** [comment]
I wish I could help just not really seeing anything beyond Netty issues / multiplayer issues. The root cause to this issue is beyond me. Maybe @pauljoda can give it a peek and find out.

**Comment by Dominance** [comment]
Spent hours trying to figure this one out to no avail closing for now as it is a rare occurrence it seems.

**Comment by Githubaccountlol** [comment]
Happened again, got the log from the first occurance this time.  Doesn't look helpful.
Lots of chromaticcraft pylons in the vicinity.

http://pastebin.com/Y3bweHQ6
