### ISSUE TITLE
Oil buckets as Magneticraft still

### ISSUE THREAD

**Issue by b0bst3r** [Beyond-Reality/Beyond-Reality-Divergence#116]
Supposed to be fixed in https://github.com/Beyond-Reality/Beyond-Reality-Divergence/issues/85 but they aren't. Oil still picks up as magneticraft and buckets consumed when filling a combustion engine.  Worst still you can't empty the oil into a BC tank and pump it as it wont go into the tank.

This makes using combustion engines with oil extremely expensive consuming 3 iron per bucket of oil put in.

**Comment by Dominance** [comment]
Fixed next release
