### ISSUE TITLE
Crash while using thaumometer

### ISSUE THREAD

**Issue by thunderpanter** [Beyond-Reality/Beyond-Reality-Divergence#118]
Scanned block of aluminium (IE) crashed to desktop http://paste.atlauncher.com/view/babd7d23
also appears to happen to completely random modded blocks.

**Comment by Dominance** [comment]
so got it to replicate adding crash report http://paste.ubuntu.com/12596295/

**Comment by TacoMage** [comment]
Also crashes when scanning the IE HV capacitor as well as an Aluminum Tinkers' Forge.

**Comment by Dominance** [comment]
@Dyonovan is the thaumcraft guru I am sure he knows whats going on with this issue. :+1:

**Comment by Dyonovan** [comment]
Seen this crash a few times. Even happens on servers. No clue what causes it. Might want to report it to @Azanor. Seems similar to https://github.com/Azanor/thaumcraft/issues/1862

**Comment by balderdk** [comment]
I would like to add to this, scanning a second Tool Station (had ones af diffrent bases, the first scanned fine, notiched the second did not have the research so scanned again) causes a client side crash, also the: 

Ferrous Ingot (Thermal Foundation) 
Mana infused ingot (Thermal Foundation)
Aluminium ingot (Immersive Engineering)

I'll keep updating as i crash :P

**Comment by Buuz135** [comment]
Fixed
