### ISSUE TITLE
Crash: Stackoverflowerror

### ISSUE THREAD

**Issue by Leftorius** [Beyond-Reality/Beyond-Reality-Divergence#119]
http://pastebin.com/sKmaiejc happens a lot if I just travel around a world (World Gen is ATG)

**Comment by Dominance** [comment]
This is a new world or old? I would think it would be new with ATG being the world gen selected.

Edit: New world as of 1.2.3

**Comment by Leftorius** [comment]
it is new and it happen even with the normal generator (tested it twice)

**Comment by Dominance** [comment]
As I am having a hard time replicating this. Can you attempt to delete this file https://github.com/Beyond-Reality/Beyond-Reality-Divergence/blob/master/config/CustomOreGen/modules/custom/BROre.xml DO NOT DO THIS in a world that you care about as it will not generate new chunks with some ores crucial to progression.
