### ISSUE TITLE
Steel Armor

### ISSUE THREAD

**Issue by recklectic** [Beyond-Reality/Beyond-Reality-Divergence#12]
Crafting of steel armor early requires Railcraft unlocked, despite being produced through Tinker's first in the progression.  The High Oven could be switched to producing Tinker's steel instead?

**Comment by Dominance** [comment]
Sure thing as other than using thaumcraft or Immersive engineering new arc furnace. Steel is only available via steelworks the other two blast furnaces have been disabled. Now just to figure out how to force it to output tinkers steel in the mold

**Comment by recklectic** [comment]
TinkersConstruct.cfg
67    # You will always get a TConstruct item from casting an ingot or block.
68    B:"Always cast TConstruct ingots"=false

I assume the ore dictionary would avoid this causing problems with other mods? I'll enable it in my worlds to see.

**Comment by Dominance** [comment]
I think you are looking at this wrong. Both railcraft and tinkers steel works steel armor can be crafted via any steel ingot.

Edit: Nevermind I see what you are saying.

**Comment by Dominance** [comment]
Fixed in 1.0.8 Railcraft steel or any type http://i.imgur.com/kZn78K3.png Tinkers steel armor as output http://i.imgur.com/R96vtQK.png
