### ISSUE TITLE
Incorrect information in Divergence Book: Sluices

### ISSUE THREAD

**Issue by TacoMage** [Beyond-Reality/Beyond-Reality-Divergence#120]
It mentions in the book that sluices can be "easily automated" with a hopper and a sifter; however, this is only partially true.  You can automate material injection with a dropper/hopper, but the sifter cannot seem to be automated as part of this chain because sluices hold their output in place in order to keep them from despawning rather than allowing them to travel down to the end of the flow for collection.  I've tried a number of various setups and sluices do not appear automatable with only a dropper and sifter as suggested by the book.  It's also possible that I'm just missing something here.

You can probably automate with some kind of item-collection (such as golems, drones, or what have you), but I don't think that was the meaning the book was going for.

Was this something based on an earlier version of HarderOres, maybe?

**Comment by Dominance** [comment]
Yeah this was based on a earlier version. Will get it corrected.

**Comment by Dominance** [comment]
Fixed next release https://github.com/Beyond-Reality/Beyond-Reality-Divergence/blob/master/config/enchiridion/books/BeyondRealityDivergence.json#L1061
