### ISSUE TITLE
Bright and transparent containers, statues, machines

### ISSUE THREAD

**Issue by dkalnins** [Beyond-Reality/Beyond-Reality-Divergence#127]
When I look at certain objects (statues, chests, sifter, signs) they look really bright, flicker and are semi-transparent. If I change the angle, or move about they flip back to normal. I've tried playing the game with things in this state but it gives me a headache. I've tried both with and without the divergence resource pack and the same thing happens either way.
![2015-09-30_12 24 04](https://cloud.githubusercontent.com/assets/3414804/10183054/db4687c6-676e-11e5-8063-192fe9eedf84.png)
![2015-09-30_12 24 10](https://cloud.githubusercontent.com/assets/3414804/10183053/db0824a4-676e-11e5-99f4-999695884ceb.png)

**Comment by helkarakse** [comment]
Have you tried resetting the transparency with f3+t as mentioned in the starting message?

**Comment by Dominance** [comment]
I am glad you have started the issue. It is a very much well known issue that for a good month and many hours eluded me. I of coarse not thinking it was my own mods fault never considered it. But in the end all the chairs tear through the transparency levels and it takes everything in minecrafts graphics engine to stop this from playing. https://www.youtube.com/watch?v=dQw4w9WgXcQ @pauljoda could you take a look at the chairs when you get back?

**Comment by Dominance** [comment]
All jokes aside just leave the temple as it only happens within rendering range of the chairs. Until it is fixed that is.

**Comment by pauljoda** [comment]
I'll have a look. The rendering state isn't being restored after we use it. All I'm doing is rendering a model so I'm not sure why it is doing that but these things happen.

**Comment by Dominance** [comment]
Yeah If it is not us then I have no clue. I rebuilt that temple block by painful block. Had everything placed (Signs statues and such) before tossing the chairs down. It only started when the chairs where placed for me.

**Comment by Dominance** [comment]
I Fixed this up
