### ISSUE TITLE
Traveller's gloves haste upgrade does not work

### ISSUE THREAD

**Issue by Githubaccountlol** [Beyond-Reality/Beyond-Reality-Divergence#129]
Verified working/not working by copying over a working version of ticon from Unabridged, where I saw that it does work properly, so ticon appears to be in working order (minus the issue with needing to open the mod-specific inventory screen in order to activate the gloves and knapsack).

My only suspect is Harder*, but removing the mods and attempting to load actually completely broke my pack and I had to reinstall rather than putting them back in, so I'm stuck.

Domi's suggestion of config disabling a hardness change in HarderUnderground:
A. didn't work
B. claims to be for dirt analogues only anyway, so shouldn't be affecting any global behavior

For anyone interested in experimenting with the gloves, you should know two things:
1. For them to work, you must visit the ticon-specific inventory page on your client once.  It's the armor-icon tab on the main inventory screen.  You can more easily verify correct behavior by equipping a ticon knapsack.  The knapsack tab will not exist either until you visit the correct inventory screen.
2. There is no visual or buff indicator for the gloves as far as I can tell.  However, in a pack with regular mining speeds, a 500 redstone glove makes punching stone a very, very noticeably different speed.  We all know how long punching stone the vanilla way takes.

Would love to get this fixed so we can have some early haste-tech.

**Comment by Dominance** [comment]
If someone wants to take up the helm in figuring this out. Have at it as it may take me a while to get around to fixing it.

**Comment by Dominance** [comment]
This issue may fall under the WontFix. As from my understanding tinkers for 1.7 has ceased development and shifted to 1.8
