### ISSUE TITLE
Adding Electrical Age?

### ISSUE THREAD

**Issue by Baughn** [Beyond-Reality/Beyond-Reality-Divergence#130]
I wonder if that's something you'd be open to.

Speaking for myself, I'd love to run Divergence for the next instance of my server, but I'm also spending a lot of time developing EA lately, and having Erisia (said server) around as a testbed is important to me.

I'd be happy to work with you on whatever modifications you think are necessary mod-side.

**Comment by Dominance** [comment]
I think electrical age is a great mod. Here is the issue I have with it which none are bad. Its like a turtle quarry vrs a buildcraft quarry. Both can basically do the same thing but only a hand full of users will use the turtle. Well because a quarry is readily available to them. Its a simple drop power play solution. 

With that being said again the mod is amazing in every way. As someone whos first real job was a electrician I deeply appreciate it. How do you see it fitting into divergence?

**Comment by Baughn** [comment]
In a couple of ways.

First off, I'm sure you're aware that it wouldn't be the first moderately redundant mod to be added, as Divergence is a fairly large pack. It does actually have charm points of its own, however.

I'll be mentioning things which aren't quite ready for use yet, but adding it to DIvergence isn't a short-term goal.
- https://brage.info/e9/80.html
  The power poles are one of the better ways to transport power over long distances. While the poles themselves are cheap, using them does force you to use EA power generation. EA equipment does not need to be chunkloaded, and the simulation collapses all linear lines to single units. (So, in short, it's server-friendly.)

It'd work well with railways.
- X-Ray scanners make it easier to find ore veins, if you have a rough idea of where to look. They aren't terribly useful with standard oregen, but I see them as being immensely handy with Harder Ores.
- I could tweak the autominer to handle those ores correctly, similarly to the Immersive Engineering excavator. (This does not exclude the x-ray scanner; the autominer exists at a higher tier of EA tech.)
- More speculatively, I'm plotting a large add-on pack--something I call "mechanical age"--which adds a rather complicated ore-processing system, along with other energy sinks. That'll take some time, and if the above isn't interesting enough then I'll just get back to you at whatever point I get this stuff to work.
- You could, of course, nudge people in EA's direction with your progression quests. That's up to you, and I don't think it's necessary.

Honestly, few people would play Divergence because they want to have it _easy_. If they did, they wouldn't be touching that progression system. I don't think it'd go unused.

I haven't gotten very far into Divergence, however--except in creative mode--so I could be mistaken.

**Comment by Baughn** [comment]
More generally, I'm looking for suggestions. I'm adding equipment to EA _anyway_, with the goal of making people want to use it.

What do you think would be useful?

**Comment by Dominance** [comment]
Will be adding it into the next major version. 1.2.5

**Comment by Landrash** [comment]
I would love to see some integration between Railcraft and EA.
If there's something I'm missing in Divergence right now it would be some really slow auto mining that would give me more reasons to have trains going all over the place collecting stuff.
Maybe something for EA?

If going for other suggestion it might be interesting to have auto mining for only certain minerals. 
Further integrating it into Divergence could be done with it emitting gasses like the ones found from enviromine thus making it unsuitable for deployment where players are.

**Comment by Dominance** [comment]
The EA miner is pretty decent. I have not tested it how ever all auto miners I have tested share the same flaw. They break blocks once and replace with air it seems. So due to this none of them work correctly with the Harder Ores. As all of them just break it one time replace it with air and move on, which yields almost no ore.

**Comment by Baughn** [comment]
Which is fixable. Well, I'll need to finish the current mess of a utility pole system first, though.

**Comment by Dominance** [comment]
Baughn do you use IRC or any other means to directly contact you?

**Comment by Baughn** [comment]
Sure. You can find me on Rizon or Freenode, same nick.

**Comment by Dominance** [comment]
Mind hopping over to espernet #beyondreality or just /msg me Dominance to have a quick chat!

Edit Nm on freenode just send me a pm

**Comment by Dominance** [comment]
Will be looking to include Electrical Age in the next iteration of divergence but dont have the time to do so on these final pushes.
