### ISSUE TITLE
[SCREENBUG] Screen become dark if you sit on the quest chair

### ISSUE THREAD

**Issue by hron84** [Beyond-Reality/Beyond-Reality-Divergence#131]
Is there any way to bring back the old feature of the quest chair in the temple to not make the screen dark, instead render me like if I sit on a Bibliocraft chair? I preferred that feature.

**Comment by Dominance** [comment]
Nothing has changed as far as the sitting goes. Only that your sitting on one in a room that is only 2 blocks high. Your heads in the ceiling.

**Comment by hron84** [comment]
It should be possible, however, usually if my head bugs in in a block, I can see a distorted version of the  texture of the affected block. However, in this case, the entire screen becomes dark and as I saw, the temple is no longer built from dark block (but a little brown-ish).

**Comment by Dominance** [comment]
Try to go into a test world in creative and place down a chair with ether open sky or a 3 blocks high room.

**Comment by hron84** [comment]
I'll try it when my laptop start working again... I can't promise it will happen soon. :disappointed:
