### ISSUE TITLE
Ore Dowsing Crash

### ISSUE THREAD

**Issue by helkarakse** [Beyond-Reality/Beyond-Reality-Divergence#132]
Server crashes when the ore dowsing rod is used.

Crash log: http://pastebin.com/tHuDcCkZ

**Comment by Dominance** [comment]
https://github.com/rosche/ore-dowsing/issues/2

**Comment by Squall0182** [comment]
(copied from the other ore dowsing thread)
http://pastebin.com/ECqiAmvM same here, tried with any dowsing machine, works fine until it detects a block, heres the other two reports aswell:
http://pastebin.com/JvW8B8Sd
http://pastebin.com/kiATeUbh

**Comment by rosche** [comment]
I believe this is fixed in release 0.6 of Ore Dowsing.  Thanks for the report.

**Comment by Squall0182** [comment]
I can confirm, swapped the old version with the new one for this pack and it works a treat ty

**Comment by Dominance** [comment]
Fixed in 1.2.5
