### ISSUE TITLE
Items not stacking

### ISSUE THREAD

**Issue by Tasorius** [Beyond-Reality/Beyond-Reality-Divergence#134]
Some items (like cobblestone) randomly do not stack, even though they are the exact same item with the exact same ID.
The same issue as the original "Beyond Reality".

**Comment by Dominance** [comment]
Going to need screen shots or something to go off. there is a few types of cobble stone that use different meta id's Depending on if they are from Harder Underground which have different broken levels. Or vanilla cobble which still exist.

**Comment by Tasorius** [comment]
Apparently it stacks now... It may just have been me not registering that there were 32 cobble in that stack. I can't get it to happen again, if it is a thing though.

The problem is still there in the original though, with no visual differences (including the ID and damage value). An image wouldn't solve anything, as the ID etc. text is exactly the same...

**Comment by Dominance** [comment]
I cannot reproduce this issue myself.

**Comment by Tasorius** [comment]
So it may only be a problem in the non Divergence version...

**Comment by Dominance** [comment]
Wait what pack was this happening too? As in divergence other than what I explained I cannot replicate the exact same cobble stone not stacking.

**Comment by Tasorius** [comment]
Ít was a thing in "Beyond Reality" and still is, unless my world is
corrupted, but I may have been wrong about it being a thing in "Beyond
Reality Divergence", if I was confused by the 32 instead of 64 stacks.

**Comment by Dominance** [comment]
This is the issue tracker for Beyond Reality Divergence. If it is related to beyond reality (with greg tech) Here is the issue tracker for that mod pack https://github.com/Beyond-Reality/BeyondRealityModPack/issues
