### ISSUE TITLE
Food rotting on certain items?

### ISSUE THREAD

**Issue by ugrashrath** [Beyond-Reality/Beyond-Reality-Divergence#135]
There's a few different items that have food rot, and I'm not sure if it was intentional or not.

Gluttony shards from Forbidden Magic, Mana beans from Thaumcraft, and blue Gelatinous Slime from Tinkers' Construct.

http://i.imgur.com/KQ1zXX1.png
http://i.imgur.com/1FCvho4.png
http://i.imgur.com/82uVxJM.png

**Comment by Dominance** [comment]
ok I will get to fixing already knew about gluttony shards https://github.com/Beyond-Reality/Beyond-Reality-Divergence/commit/b8ebc0b21f1ccb0f65d287b85acccb58fc90fb5f Will get to the other two and push a hotfix later today.

**Comment by Dominance** [comment]
Adding thaumcrafts zombie brains to list.

**Comment by Dominance** [comment]
Should be good to go in 1.2.5
