### ISSUE TITLE
1.2.4 - Can't craft crafting table?

### ISSUE THREAD

**Issue by mrbaggins** [Beyond-Reality/Beyond-Reality-Divergence#136]
Spawned in a rainbow forest, have tried to use Spruce, Oak, Dark oak and birch logs, when turned into plants and placed in a 2x2 I don't get the crafting table. NEI suggests a lot of extra trees planks, but didn't see the vanilla ones in the list.

Have I had an aneurysm or is something broken?

**Comment by helkarakse** [comment]
I don't seem to have this problem. I successfully crafted a crafting table (vanilla) in my small crafting window (2x2) and in a crafting table (vanilla, 3x3).

**Comment by Dominance** [comment]
multiple attempts to replicate this. after the 12th new world spawned into rainbow forest was able to make crafting table. Can you provide a screen shot with the recipe in place that shows no output for my sanity?

**Comment by mrbaggins** [comment]
On holiday for a couple days, will update Monday with more info / video

**Comment by mrbaggins** [comment]
Updated to 1.2.5 before I remembered this, not an issue there either. Maybe just unlucky or something downloaded wrong.

**Comment by Akianna** [comment]
Latest update here, was able to make whatever out of oak wood, planks, sticks, crafting tables, and then this happened... 
![2015-10-06_15 13 43](https://cloud.githubusercontent.com/assets/15003634/10321210/19e8839e-6c3d-11e5-8e60-ef2d536bb420.png)
Can't seem to make anything out of oak wood now...acacia wood works just fine though? Kind of weird that I could, and then, when I went to make more.... couldn't.

**Comment by mrbaggins** [comment]
Is acacia a forestry one? Because that seemed to be the list in the recipe window.
