### ISSUE TITLE
Placed dirt block made quest gate impassable

### ISSUE THREAD

**Issue by wugmump** [Beyond-Reality/Beyond-Reality-Divergence#139]
I opened the second quest gate door and accidentally placed a dirt block in the entry; now it's unbreakable and I cannot remove it.

**Comment by wugmump** [comment]
![2015-10-02_11 20 18](https://cloud.githubusercontent.com/assets/552667/10250239/a3270778-68f7-11e5-88e0-c763cc6af109.png)

**Comment by helkarakse** [comment]
If you're in single player, you can open the game to LAN, enable cheat mode, turn on creative, then break the block.

**Comment by Dominance** [comment]
Yeah there is nothing I can do to adjust this even if I wanted to. Will just have to do what Helk mentioned or get a admin to assist you
