### ISSUE TITLE
Satchels still in Loot Bag

### ISSUE THREAD

**Issue by ugrashrath** [Beyond-Reality/Beyond-Reality-Divergence#140]
We updated our server to 1.2.4 yesterday.

I was out killing mobs, and then opened a bunch of loot bags, and in an Uncommon Loot Bag, I found another satchel, but I believe the latest patch notes said they were supposed to have been removed.

http://i.imgur.com/kpxXMnx.png

**Comment by Dominance** [comment]
Thanks for the heads up yeah just noticed I did not remove it from both locations. Will have it fixed up next version.
