### ISSUE TITLE
Can't craft any of the items from Tube Transport System after unlocking

### ISSUE THREAD

**Issue by Snorsby** [Beyond-Reality/Beyond-Reality-Divergence#145]
I'm unable to craft any of the items from the mod "Tube Transport System" even after I've unlocked it in the quest book and have gone to the temple to sit in the chair to unlock the mod. I'm able to look up the recipes in NEI however when I place the items in either a crafting table, or in a crafting station, the crafted item won't show up in the right slot to take out.

**Comment by Dominance** [comment]
The recipes do not use the ore dictonary currently. so the stone is possibly trowing you off. Have it fixed next version until then you minecraft stone. craft normal cobble with ether 2 unstable cobble + 2 sticks or a chisel then smelt it to attain normal stone.
