### ISSUE TITLE
Black Screen when sitting in chairs in temple and things becoming transparent

### ISSUE THREAD

**Issue by PlasmaticPi** [Beyond-Reality/Beyond-Reality-Divergence#148]
Whenever I sit in one of the chairs in the temple my screen turns black. I can move around and place stuff apparently but in order to see anything other than a pure black screen I have to save and quit to title and then re-open the save.

Also, certain things like chests, the statues of the people in the temple, and the skeleton in front of the temple will become partially transparent whenever you don't look directly at them. It is super weird and disconcerting.

**Comment by Dominance** [comment]
See https://github.com/Beyond-Reality/Beyond-Reality-Divergence/issues/127 and https://github.com/Beyond-Reality/Beyond-Reality-Divergence/issues/131
