### ISSUE TITLE
BRD 1.2.5 - can't craft 90% of Thermal Dynamic ducts

### ISSUE THREAD

**Issue by b0bst3r** [Beyond-Reality/Beyond-Reality-Divergence#150]
Can make only Leadstone Fluxduct and Temperate Fluiduct so that's 2 out of about 20 (can't even make Itemducts).

Reason is the others require hardened glass or Hardened Lumium Glass (thermal Expansion) or Blast Glass (rotarycraft) which are all locked and because they are locked you cannot use them to craft the ducts/items.

**Comment by Dominance** [comment]
https://github.com/Beyond-Reality/Beyond-Reality-Divergence/commit/af5d54cac81c6e5a78ca314b36b6d152f23c150b Still testing but yeah should be fixed.
