### ISSUE TITLE
Delete - Botched server install

### ISSUE THREAD

**Issue by Squall0182** [Beyond-Reality/Beyond-Reality-Divergence#151]
Every time I jump up and place a block below I get an internal server error. I have tried cobble, planks  (building an underground modular storage) and every one results in an internal server error. The block is placed, and i connect on top of the blocks but I have to relog each block

**Comment by Squall0182** [comment]
Just tried placing blocks to my side, same issue

**Comment by Squall0182** [comment]
Testing it further, seems to be mainly vanilla and non-functioning blocks (chisel confirmed as one) that are affected, and they don't leave my inventory but are placed, essentially duping items. Heres the log: http://pastebin.com/EG9AhmYw

**Comment by Squall0182** [comment]
Ignore all the above, the server was a failed install

**Comment by Dominance** [comment]
All good bud! In the future just close the issue. Keep them coming and thanks for posting :)
