### ISSUE TITLE
Modular crusher makes IE quartz dust from nether quartz ore

### ISSUE THREAD

**Issue by Belgabor** [Beyond-Reality/Beyond-Reality-Divergence#153]
According to NEI it's supposed to make nether quartz. Since the dust only has use inside IE imo it should make the 4 quartz as NEI promises.

**Comment by Dominance** [comment]
![Image quartz](http://i.imgur.com/86535qO.png) ![Image of quartz ore](http://i.imgur.com/QNRznJa.png)

**Comment by Dominance** [comment]
https://github.com/Beyond-Reality/Beyond-Reality-Divergence/commit/1450453cd0d2ceddb0035ff37ccd25f89a63a59a
