### ISSUE TITLE
Wont start up reason: One of the mods requires 1.8.jar

### ISSUE THREAD

**Issue by Jamzs3** [Beyond-Reality/Beyond-Reality-Divergence#154]
I cannot find the mod which requires 1.8.jar but it stops me from playing the mod pack which is very annoying after an hour of trying to find that mod. The pop up says download 1.8.jar but which mod needs it? why is it not compatible with 1.7.10? Please fix. (using latest beta)

**Comment by mrbaggins** [comment]
Sounds like you're missing Java, not a 1.8 jar.

https://java.com/en/download/

Otherwise, post more info.

**Comment by Dominance** [comment]
Yeah java 8 is required as mr baggins suggested. Has nothing to do with the minecraft version. Thanks mr baggins!!!
