### ISSUE TITLE
Storage drawers wont release items

### ISSUE THREAD

**Issue by mrbaggins** [Beyond-Reality/Beyond-Reality-Divergence#155]
Can add items to storage drawers, can't remove items. Tried left, shift left, open hand left, open hand shift left, none work.

Edit: Can remove items when holding TC axe / pick etc. Manasteel sword, building blocks and open hand cannot.

**Comment by Dominance** [comment]
Another REALLY strange issue. I cannot replicate this? Been using storage drawers in my own base with no issues at all.

**Comment by mrbaggins** [comment]
Hrm... I'll keep investigating then. Really annoying currently, but workable. I pretty much always have tools on the hotbar. 

World file, if you want to test. The number is just what version the world started on. To get to where I was having problems, follow the road out of the temple south east to the village, go in the building with the windmill on top.
https://onedrive.live.com/redir?resid=6F9AA74EE20EC48B%211977

**Comment by mrbaggins** [comment]
Oddly, using an open hand worked earlier today. About to log in to 1.2.5.2
