### ISSUE TITLE
Not able to craft with Oak wood?

### ISSUE THREAD

**Issue by Akianna** [Beyond-Reality/Beyond-Reality-Divergence#156]
Latest update here, was able to make whatever out of oak wood, planks, sticks, crafting tables, and then this happened...
![2015-10-06_15 13 43](https://cloud.githubusercontent.com/assets/15003634/10321334/aca9010e-6c3d-11e5-9a8f-207f1600576e.png)

Can't seem to make anything out of oak wood now...acacia wood works just fine though? Kind of weird that I could, and then, when I went to make more.... couldn't. Note, was using the Gray Chromatic trees, but now no oak works. But the acacia wood works from those trees. Erg...make that also birch, jungle, and dark oak not working as well.

**Comment by Dominance** [comment]
This is a long shot but try to download http://minetweaker3.powerofbytes.com/download/MineTweaker3-1.7.10-3.0.9C.jar and replace the current version 3.10.0 of mine tweaker with that one boot up and let me know how it goes.

**Comment by Akianna** [comment]
Okay, will do and will let you know.
Just completely exited out of the game, going to see if a restart works first.

**Comment by Akianna** [comment]
Okay, so..... A complete restart did help, but do you know if the file you suggested would make it so that it wouldn't happen again? Either that, or I could play for a bit and pay attention to what I do, and see if I can make it happen again now that I know a complete restart "fixes" it?

**Comment by Akianna** [comment]
Well... hmm... I did everything I could think of that I did before it happened.... I couldn't recreate it. Maybe I just had bad luck like that other guy did. I will keep your link in mind though, and will let you know if it happens again and maybe I can figure out what I did.... Thank you for the help though. I should have done the restart before posting.  I did a quit game to menu and restart, but was stubborn about having the game reload again lol.

**Comment by Dominance** [comment]
I have recenlty had a issue trying to craft a auto chisel similar to this. I changed up the slabs up top with another material and it ended up working. Thing is its almost impossible to try and find the root cause.

**Comment by Dominance** [comment]
I think I may have this strange stuff sorted.

**Comment by Dominance** [comment]
Should be good 1.2.5.2
