### ISSUE TITLE
Ingot/block conversion

### ISSUE THREAD

**Issue by Snake597** [Beyond-Reality/Beyond-Reality-Divergence#157]
Pack has multiple types of various materials in, not sure if issue pertains to other blocks but unable to convert steel from one type to another, e.g. the recipe for tinker's steel block > immersive engineering steel block doesn't work, only gives ingots, steel not listed in lexicon so also not a possibility

**Comment by Dominance** [comment]
https://github.com/Beyond-Reality/Beyond-Reality-Divergence/blob/master/scripts/Immersive%20Engineering.zs#L44 Its been added for Immersive Engineering steel. Just craft a tinkers steel block and switch it to immersive. I cannot help the mod author does not use ore dictionary in the recipes. All I can and have provided is a method to attain IE steel. http://i.imgur.com/aE3H0Cc.png Works with ether Tinkers / Railcraft Steel blocks.  This was added in 1.2.5
