### ISSUE TITLE
Crash while interacting with Modular Systems I/O block on a crusher.

### ISSUE THREAD

**Issue by tentonaxe** [Beyond-Reality/Beyond-Reality-Divergence#158]
Shift right clicked on I/O, changed it to not auto, crushed some iron ingots, then when switching it back to auto the below error happened.

http://paste.ubuntu.com/12710839/

**Comment by Dominance** [comment]
@pauljoda

**Comment by pauljoda** [comment]
What was it outputting to

**Comment by tentonaxe** [comment]
Modular systems furnace

**Comment by pauljoda** [comment]
Great. So either way its my problem.  I'll look into it

**Comment by Belgabor** [comment]
Probably this one TeamCoS/Modular-Systems#101

**Comment by Dominance** [comment]
Closed mod side
