### ISSUE TITLE
No recipe for Augmentations and Amplifications`

### ISSUE THREAD

**Issue by TAHerman** [Beyond-Reality/Beyond-Reality-Divergence#160]
The book says that NEI has the recipe for augmentations. I couldn't actually get the recipe for amplifications to work and I can't even find the recipe for the augmentations. I may be missing something but I'm not sure what. I looked at some code and tried using chipsets, iron tough rods, ferrous gears, copper ingots, and charcoal. That didn't work.

**Comment by Dominance** [comment]
What version are you playing? Here is a picture for Passive Amps http://i.imgur.com/FMq8Uq0.png and one for Augumentations.

**Comment by Dominance** [comment]
update to 1.2.5.2 it fixes this issue. Cannot replicate in newer version.

**Comment by TAHerman** [comment]
I am on 1.2.5.1 in the AtLauncher. I see the update option so I will update now. Thanks.

**Comment by TAHerman** [comment]
I just updated to 1.2.5.2 and NEI is still not showing the recipes for me. I find the augmentations in NEI and select one (starting with "exceptional") and it doesn't show me anything. I have no idea what the recipe is for the lower tier (or any tier) of augmentation. I saw your image for the amplification but do you have one for the lower tier as I can't see the recipes for the lower ones either.

I thought the recipe for the exceptional augmentation was charcoal, redstone chipset, toughrod, copper and nickel (ferrous) gear but that doesn't seem to be working. I have that all in my assembly table and I'm not seeing the option for the augmentation.

I must be doing something wrong but I'm not seeing what.

**Comment by TAHerman** [comment]
@Dominance I saw the hot fix and updated to that as well (1.2.5.3). I rebooted my system in case there was something else going wrong. I absolutely cannot see the recipe for amplifications or augmentations in NEI.I see the recipes for everything else.
