### ISSUE TITLE
BC not removed when updated to 1.2.5.2

### ISSUE THREAD

**Issue by mrbaggins** [Beyond-Reality/Beyond-Reality-Divergence#161]
![Screenshot](http://i.snag.gy/0cBRY.jpg)

**Comment by mrbaggins** [comment]
Also the BRCore at the bottom.

I've removed the 7.1.8 and 1.5.7b11 versions respectively from the mods folder, things seem okay

**Comment by Dominance** [comment]
Its strange that this is happening. More of a Launcher issue than a pack issue. Happend to me a vew versions ago. As you can see BRCore = https://github.com/Beyond-Reality/Beyond-Reality-Divergence/blob/master/Divergence.xml#L132 Buildcraft = https://github.com/Beyond-Reality/Beyond-Reality-Divergence/blob/master/Divergence.xml#L150 Both are only listed once with the correct MD5. Not really sure why its refusing to remove old mods.
