### ISSUE TITLE
Dowsing Rod does not recognize hard redstone ore

### ISSUE THREAD

**Issue by TacoMage** [Beyond-Reality/Beyond-Reality-Divergence#164]
All the harder ores work correctly with the dowsing rod except Hard Redstone ore.

My suspicion is that Ore Dowsing isn't detecting the blocks because, unlike all the other Harder Ores ore blocks, hard redstone does not have an oredictionary entry.

**Comment by TacoMage** [comment]
I just verified that it was the oredictionary issue.  I added this to the Basic.zs and redstone works with Ore Dowsing now:

`<ore:oreRedstoneHard>.add<HarderOres:ore_redstone>`

**Comment by Towsty** [comment]
Not sure if this is intentional or not, but it seems that the fire flowers for Redstone indication are fairly misleading. When taco added the Redstone to the ore dic we noticed sometikes the Redstone indicators don't have Redstone within that chunk.

**Comment by Dominance** [comment]
I am not 1000% sure how exactly the flowers generate over the ores. I do know that it does not mean there is one directly below it. I think its within 48 blocks IIRC
