### ISSUE TITLE
Temple Not Spawning In Multiplayer Worlds

### ISSUE THREAD

**Issue by rocket24251** [Beyond-Reality/Beyond-Reality-Divergence#165]
I recently started a server with the Divergence pack, but the temple isn't spawning. I've traveled 1,000m in every direction on 4 seeds before deciding to use seeds from singleplayer worlds. In two different seeds that had the temple in SP worlds, the temple failed to spawn. Please tell me this is a simple fix! :(

**Comment by Dominance** [comment]
I have had this come up in the past without being able to figure out why. The easy way to go about doing this. find a flat area on a map do --->     /#gen Temple4.8    <----- Caps matter. It will bring up a overlay of the temple if you like the way it looks do /#confirm as instructed. If you wish to contribute to fixing the issue for others please upload your latest FML logs corresponding to a world where the temple did not spawn.

**Comment by rocket24251** [comment]
Thank you so much! Unfortunately I do not have any of those logs, as I have deleted all of those worlds... If it happens again I will share them!

**Comment by Dominance** [comment]
kk
