### ISSUE TITLE
Thermal Dynamics Covers locked with Progression 

### ISSUE THREAD

**Issue by Towsty** [Beyond-Reality/Beyond-Reality-Divergence#166]
It seems that you cannot place the covers from Thermal Dynamics as they required Malisis Doors and Witchery to be unlocked? This is on version 1.2.5, will check with latest version later today.

**Comment by Dominance** [comment]
Next version wil be good. Mix up with stuff like 
"item": "ThermalDynamics:cover 0 {Meta:0b,Block:\"witchery:daylightcollector\"}"
