### ISSUE TITLE
Tech Research Unaccessable

### ISSUE THREAD

**Issue by MajorWolf2** [Beyond-Reality/Beyond-Reality-Divergence#169]
I finished the tutorial and I noticed that one of the Tech Research quest, I'm assuming the one you start with, isn't accessible as it outside of the GUI. I can access all the other ones that I can start.

**Comment by b0bst3r** [comment]
Go to video settings and change GUI Scale to something smaller temporarily so you can access it.  Also latest version doesn't have that problem.

**Comment by Dominance** [comment]
Majorwolf have you tried to update to 1.2.5.2 + ? This issue should of been resolved https://github.com/Beyond-Reality/Beyond-Reality-Divergence/issues/105

**Comment by MajorWolf2** [comment]
I made this without checking for an update. It's been fixed.

**Comment by Dominance** [comment]
Cool thanks for posting a issue! keep them coming if you find anything else
