### ISSUE TITLE
Tech Augmentation and magic Amplification recipes

### ISSUE THREAD

**Issue by vagaprime** [Beyond-Reality/Beyond-Reality-Divergence#170]
NEI is not showing the crafing recipes for the Tech Agu, or Magic Amp's. I am running the beta hotfix 1.2.5.3. I have looked into the scripts file and the recipes are missing from Buildcraft, botania and BCA script files.

Link to Imgur for pictures
http://imgur.com/a/hYTUm

**Comment by Dominance** [comment]
Reinstall the pack, on the optional side http://i.imgur.com/AjkxiMj.png Choose your mode then hit ok then hit play then win!

The next release I will attempt to make this a bit more obvious as it is not currently.

**Comment by vagaprime** [comment]
Ok they are showing up now.

**Comment by vagaprime** [comment]
On a unrelated note. Should the wooden tracks be craftable early game?

**Comment by Dominance** [comment]
Yes wooden rails are craftable early game. Look for " wooden rails " added by tinkers construct
