### ISSUE TITLE
Rainbow Forest - Rainbow Trees

### ISSUE THREAD

**Issue by recklectic** [Beyond-Reality/Beyond-Reality-Divergence#18]
These "rare" trees from this biome drop 3+ random drops per leaf.  These drops include bone meal, lapis, golden/jeweled apples, and saplings to grow at least two more of them from what I've seen. The drops from one of these trees can fill a double chest.

planted in a 2x2 like jungle trees

**Comment by recklectic** [comment]
Chromaticraft white tree leaves drop bone meal, blue trees lapis, as well.

**Comment by Dominance** [comment]
Yeah this is a huge balance concern for sure. I was just messing around breaking one early today and see this as well

**Comment by Dominance** [comment]
Changed a few things for 1.0.9 Alpha
D:"Rainbow Leaf Gold Apple Drop Percentage"=0 from 0.25
I:"Vanilla Dye Drop Percentage"=5 from 60 default is 100
I:"Rainbow Forest Animal Density"=3 from 6 This should help reduce the amount of monsters as well I think.
