### ISSUE TITLE
Copper raw ore not smeltable

### ISSUE THREAD

**Issue by ghost** [Beyond-Reality/Beyond-Reality-Divergence#180]
I am not the most up to date on the pack but it seems that raw copper ore is not smeltable in a furnace while other raw ores (like gold) are perfectly able to. Picture below describing this. Let me know if you need anything else Dominance. :)

http://imgur.com/a/T7K2i

**Comment by mrbaggins** [comment]
Not that it solves the problem, but generally you want to be using a windmill pretty quickly anyway
