### ISSUE TITLE
Sound crash.

### ISSUE THREAD

**Issue by vagaprime** [Beyond-Reality/Beyond-Reality-Divergence#181]
So I am not sure what happened here all I do know is that the first crash happened while shift clicking some items into a wooden hopper and the second crash happened shortly after relaunching the pack and loading up my world. Both crashes sent me back to desk top. The only mod that I added to the back was Optifine.

First crash: http://pastebin.com/wn5BdZcf

Second crash: http://pastebin.com/pJDVtQXu

**Comment by Dominance** [comment]
One thing you can try is to disable Sound filters which is a optional mod. What types of sounds is your character near at the moment?

**Comment by vagaprime** [comment]
The grind stone. Also after I launched the back once more after the second crash I was able to play the world with out it crashing.

**Comment by vagaprime** [comment]
Also looking over my mod list. I did not have sound filters installed or active when my world was crashing.

**Comment by Dominance** [comment]
ok thanks for the reply I think this may be related to only reasonable realism as I have ruled out everything that should effect the sound. @draco18s could you take a peak and see if it is related?

**Comment by Draco18s** [comment]
I doubt this is me.  I worked really hard to make the grindstone sound work properly.  Because it is a concurrent modification error, it would hit my HashMap first (which is modified before accessing Minecraft's sound code).

**Comment by mrbaggins** [comment]
I got a concurrentModification crash yesterday when near my millstone, but I didn't link it with anything I was doing at the time. In fact, it was as I right clicked a door. Only reason this seemed notable was that I have never crashed before this version that I remember.

**Comment by Draco18s** [comment]
My sound handling code hasn't changed since...oh god, easily pre-version 1.
