### ISSUE TITLE
Botania Floral fertliser recipe wrong

### ISSUE THREAD

**Issue by mrbaggins** [Beyond-Reality/Beyond-Reality-Divergence#193]
Floral fertiliser is supposed to be able to use any colour floral powders, but the recipes will only work with White in a certain spot.

**Comment by Belgabor** [comment]
That's normal, the spot is for bone meal.

**Comment by mrbaggins** [comment]
Sure, but there's two recipes right?

One is bonemeal + 2 red and 2 yellow dye. Easy.

The other is Bonemeal, plus white powder, plus 3 any powders. That's wrong. It's supposed to be Bone + 4 any powders.

**Comment by Belgabor** [comment]
It shows any kind of white dye plus four other colors for me.

**Comment by mrbaggins** [comment]
Even the top right one?Because mine is consistently that the top 2 can only be white, one bone meal or white powder, the other one white floral powder only.

**Comment by Dominance** [comment]
You are very talented at generating reports I cannot replicate. You have two recipes one being pretty much any combination and a white dye http://i.imgur.com/ouXnlcm.png the other being red red yel yel white http://i.imgur.com/KUTOGF9.png Botania's Floral fertliser recipe has not been altered in the pack.

**Comment by mrbaggins** [comment]
Nice to know I'm special.

It's the one covered by your chroma label. THAT one must always be a white floral powder for me. Double checking now with 1.6 just to confirm

Edit: And it's fixed in 1.6 apparently. I reported this from 1.5 I think, or maybe before the 1.6 hotfix. I am certain of the problem though, as I had no light grey flowers and needed to make fertiliser, and it wouldn't let me use bonemeal + 4 black powders.
