### ISSUE TITLE
FPS issue with Ye Olde Tanks/BC/TiCo

### ISSUE THREAD

**Issue by Belgabor** [Beyond-Reality/Beyond-Reality-Divergence#194]
Not sure what part is the culprit, but this setup floors my FPS:

![2015-10-16_17 14 31](https://cloud.githubusercontent.com/assets/36589/10545713/6aad224a-742a-11e5-858c-7c7731130951.png)

It's somewhat ok with BC tanks, but it now and then can drop my FPS as well.

**Comment by mrbaggins** [comment]
6fps down from what? EG: 6 from 20 isn't as bad as 6 from 120+

**Comment by Belgabor** [comment]
It fluctuates, I usually get around 20 with this pack. The shown setup keeps it constantly at 5-6.

**Comment by Dominance** [comment]
Ive managed to get it below 30 by doing stuff like this http://i.imgur.com/DxHdumV.jpg pretty tall tcon set up as well http://i.imgur.com/z38XhC0.png This is constantly feeding it raw ores that smelt as fast as nuggets. I think the slow down on my end is the 1000+ raw ores that have spewed out. Not saying its not a issue how ever it is something that seems to be ether only on your end. Or linked to something else within your render range. I will suggest to remove the redstone motor as its not needed. The fluid auto ejects into wooden pipes.

**Comment by Dominance** [comment]
Also did try it with 4 redstone engines with similar numbers. I normally get around 30fps while playing divergence myself around machines and such.
