### ISSUE TITLE
Matter Overdrive console spam

### ISSUE THREAD

**Issue by Crumbology** [Beyond-Reality/Beyond-Reality-Divergence#195]
"There was a problem getting a Matter Entry."  in console, this was mentioned in chat in BR so not much more info than this.

This is most likely a problem with the way MO builds its matter lists, it's all kept in registry.reg in it's config folder which is created when a single player world is loaded if it does not already exist.  It never updates the list once created, so any additions or removals from a pack need this file regenerating by deleting it and running a single player world or some matter entries will be wrong or nonexistent.

**Comment by LacSappy** [comment]
It happened on my SMP server (manual update) and in single player (auto update with the atlauncher).

This the the message:

18:16:28 CONSOLE: [Matter Overdrive]: There was a problem getting a Matter Entry.
18:16:28 CONSOLE: [Matter Overdrive]: There was a problem getting a Matter Entry.
18:16:29 CONSOLE: [Matter Overdrive]: There was a problem getting a Matter Entry.
18:16:29 CONSOLE: [Matter Overdrive]: There was a problem getting a Matter Entry.
18:16:29 CONSOLE: [Matter Overdrive]: There was a problem getting a Matter Entry.
18:16:29 CONSOLE: [Matter Overdrive]: There was a problem getting a Matter Entry.
18:16:29 CONSOLE: [Matter Overdrive]: There was a problem getting a Matter Entry.
18:16:30 CONSOLE: [Matter Overdrive]: There was a problem getting a Matter Entry.
18:16:30 CONSOLE: [Matter Overdrive]: There was a problem getting a Matter Entry.
18:16:30 CONSOLE: [Matter Overdrive]: There was a problem getting a Matter Entry.
18:16:30 CONSOLE: [Matter Overdrive]: There was a problem getting a Matter Entry.

**Comment by Dominance** [comment]
Already on top of it https://github.com/simeonradivoev/MatterOverdrive/issues/254

**Comment by mrbaggins** [comment]
Is that not related to the issue I've mentioned in the past https://github.com/Beyond-Reality/Beyond-Reality-Divergence/issues/83

**Comment by Dominance** [comment]
Yes @mrbaggins after trying for many hours to figure it out on my own. Or to see if it was a pack related issue. I gave up and reported.

**Comment by mrbaggins** [comment]
Ah okay, misunderstood

**Comment by Dominance** [comment]
For now the matter calculations are turned off. This fixes this issue but breaks that portion of the mod.

**Comment by LacSappy** [comment]
Hey Dominance,

the issue with the Matter Entry is back (Beyond Reality:Divergence v1.2.7)

**Comment by bobum** [comment]
+1 
Yes it is...

**Comment by Yorkforce** [comment]
Disabling the following in the config stopped the spam:

```
B:"automatic matter calculation from furnace"=false
B:"automatic matter calculation from recipe"=false
```

Not entirely sure what that will break however but the log file was 188MB on first startup with 2 mins uptime, it would have very quickly created a massive log file.
