### ISSUE TITLE
Regular (stick+coal/charcoal) torch recipe doesn't use oredict stick

### ISSUE THREAD

**Issue by Belgabor** [Beyond-Reality/Beyond-Reality-Divergence#197]
Intentional? Means you can't use Growthcraft bamboo, which is in the stick oredict.

**Comment by Dominance** [comment]
While it is a bug. After looking into it, Seems to be something that is hard coded with tweaks taking over the amount per craft. I could add a recipe but it would not work as the default would override it. something like this 
recipes.addShapeless(minecraft:torch \* 6, [ore:stickWood, minecraft:coal:*]);

If you did do something along the lines of this 
recipes.removeShapeless(minecraft:torch, [minecraft:stick, minecraft:coal:*]);
It turns off all crafting.
