### ISSUE TITLE
"Some" Crashes :P

### ISSUE THREAD

**Issue by Buuz135** [Beyond-Reality/Beyond-Reality-Divergence#2]
A NPE when looking at some tinkers books: http://pastebin.com/Au4sRjVE
A worldgen crash with fastcraft and RWG: http://pastebin.com/EdemD6RZ
 A crash when placing a dense cable next to a compact machine and a corrupting world: http://pastebin.com/WKirfaKG
 Dunno why is calling the mekanism api.

**Comment by Dominance** [comment]
Reworked!
