### ISSUE TITLE
a problem with /help

### ISSUE THREAD

**Issue by hmbigburt** [Beyond-Reality/Beyond-Reality-Divergence#20]

**Comment by hmbigburt** [comment]
every time you cycle throught the /help commands (/help,2-6) it seems to cause a crash.

**Comment by Dominance** [comment]
Toss the crash report in the issue I will check it out asap

**Comment by hmbigburt** [comment]
doesn't provide me with any, just shuts me down back to the AT launcher.

**Comment by Dominance** [comment]
Got cha well I may have fixed this by totaly breaking the /help command all together cheers!
