### ISSUE TITLE
Chromaticraft Lexicon Losing pages

### ISSUE THREAD

**Issue by Chaoticxzombi** [Beyond-Reality/Beyond-Reality-Divergence#205]
Don't know if this is just me but when I died with my Chromaticraft
Lexicon, I lost all progress on the main page but I have all the pages I had in the book prior to dying. Can you please look into this.

**Comment by Dominance** [comment]
I will look into this asap. first I have heard of a issue such as this.

**Comment by Crumbology** [comment]
Chromaticraft knowledge requires the actual knowledge fragments to be slotted into the book, these are lost when the book is.

You can replace these fragments by opening the book and selecting the middle tab on the right, then click on the fragments to copy if you have ink and paper in your inventory.  All lost knowledge can be regained this way.

**Comment by Belgabor** [comment]
I don't think they are lost, they just have a specific slot they go into (after you close and reopen the content interface). Scroll and you will find them.

**Comment by Crumbology** [comment]
The actual knowledge fragments are kept in the book, so if you lose that specific book they are gone, You have to remake them using the method I mentioned.

**Comment by Buuz135** [comment]
Fixed
