### ISSUE TITLE
Crafting netherportal key

### ISSUE THREAD

**Issue by tiLa-** [Beyond-Reality/Beyond-Reality-Divergence#206]
Crafting a netherportal key with enchanced inventories worktable didn't unlock the achievement Nether Unlocked. I first thought I had to unlock vanilla minecraft achievement "We need to go deeper" to make it work, but it didnt help. Crafting the keys with normal inventory crafting grid worked thou.

**Comment by Dominance** [comment]
https://github.com/Beyond-Reality/Beyond-Reality-Divergence/commit/34e56319fdf480a71777a2d9dd7542ae23fcdd38 Not really a fix but a prevention.
