### ISSUE TITLE
Pulverized coal integration

### ISSUE THREAD

**Issue by Crumbology** [Beyond-Reality/Beyond-Reality-Divergence#208]
Pulverized coal can't be made in a railcraft rock crusher or modular systems grinder.

**Comment by Dominance** [comment]
Seems it missing from Modular systems is a mod issue. Adding to railcraft only.

**Comment by Dominance** [comment]
https://github.com/Beyond-Reality/Beyond-Reality-Divergence/commit/c726c2c648ff4cc275e2b47209992329d436b5dc
