### ISSUE TITLE
Redstone dust Shift click causes internal server error

### ISSUE THREAD

**Issue by SkuxxDeluxe** [Beyond-Reality/Beyond-Reality-Divergence#209]
Shift clicking with redstone dust causes an internal server error on the creation of the stacksonstacks stack

**Comment by SkuxxDeluxe** [comment]
Shift clicking with any dusts (and with bricks) results in the same error

**Comment by primetoxinz** [comment]
are you using cauldron? because I don't get this

**Comment by Dominance** [comment]
I do think it is ether a cauldron or bungie issue myself.

**Comment by SkuxxDeluxe** [comment]
Hm. Is cauldron not recommended for servers? Thanks for the replys.

**Comment by Dominance** [comment]
Should be fixed up next version 1.2.7 ETA 10/22
