### ISSUE TITLE
Server Mine Tweaker issues.

### ISSUE THREAD

**Issue by SkuxxDeluxe** [Beyond-Reality/Beyond-Reality-Divergence#210]
The client and server side recipies for Transport tubes arent matching, and trying to craft it results in it going back into the crafting grid. (yes its unlocked and have sat in chair)

This happens with  the Nether key too.

**Comment by Dominance** [comment]
Are you running your own server or playing on one? If on your server can you provide the minetweaker logs and console logs when doing /mt reload on the server. Both your client's logs when the server preforms this command and your server logs as well.

**Comment by Dominance** [comment]
https://github.com/Beyond-Reality/Beyond-Reality-Divergence/issues/211

**Comment by SkuxxDeluxe** [comment]
Clientnside i only get "scripts reloaded". Ill get you the server side today.
Thanks for the reply.

**Comment by SkuxxDeluxe** [comment]
Sorry, just updated from 1.2.6.2 to 1.2.6.3 and not having these problems anymore. My appologies.
