### ISSUE TITLE
Lootable Bodies randomly not forming.

### ISSUE THREAD

**Issue by Crumbology** [Beyond-Reality/Beyond-Reality-Divergence#215]
Lootable corpses seems to randomly not generate a corpse, causing you to lose all your stuff with no chance of recovering any of it, if there is no fire or lava they should survive anything according to the configs.

With a long-term gameplay pack this causes days/weeks of effort to go boom in a second due to a mod glitch, extremely disheartening,   I can't see any issues on the corpses github, but it has def happened a few times now to various people, maybe time to consider a diff grave mod?

**Comment by foopex** [comment]
What are the alternatives?

**Comment by b0bst3r** [comment]
Keep Inventory on :D

**Comment by Dominance** [comment]
moved Lootable boodies to server optional (Will be select-able during server download via AT). Your choice ether buggy or nothing. 1.2.7 Until a suitable solution is found.

**Comment by b0bst3r** [comment]
Perhaps this -http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1288510-1-7-10-minecraft-graves-die-classy-updated-at
