### ISSUE TITLE
armourers workshop crash

### ISSUE THREAD

**Issue by vagaprime** [Beyond-Reality/Beyond-Reality-Divergence#216]
I am crashing to desktop when I am attempting to open the equipment library. At first I thought is was cause of the skins that I added but when I removed them I crashed once more

crash 1: http://pastebin.com/xnaKzGHt

crash 2: http://pastebin.com/WSccpc8F

edit: I have submitted a copy of this report to the Armourer's Workshop Github as well.

edit 2: RiskyKen closed the issue on his github and stated that the problem can be fixed by updating the mod to the newest version.

**Comment by Dominance** [comment]
Updated to newest in upcoming 1.2.7
