### ISSUE TITLE
Unable to craft with oak & Birch logs/planks

### ISSUE THREAD

**Issue by ImPurple** [Beyond-Reality/Beyond-Reality-Divergence#226]
For some reason crafting with birch and oak logs/ planks does'nt work on my world anymore. Is there anyway to fix this?

**Comment by Dominance** [comment]
I mean if it was every single world with every single player it would be something I could fix. Without being able to replicate the issue on my end there is little hope for fixing it.

**Comment by mrbaggins** [comment]
It's a fun bug though. Try reinstalling the pack, as that was what fixed it for me.
