### ISSUE TITLE
Bonemeal duplicates when used on grass

### ISSUE THREAD

**Issue by PaladinOne** [Beyond-Reality/Beyond-Reality-Divergence#227]
When Bonemeal is used on grass, it both places itself as a block and activates to grow plants, consuming 2 items of itself (one of which can be picked up again from the block). The issue here is that if only 1 Bonemeal is held, it still both places itself and grows plants, allowing you to grow grasses and ore indicator flowers for free.

**Comment by Dominance** [comment]
Thought I had this fixed. https://github.com/Beyond-Reality/Beyond-Reality-Divergence/blob/master/config/StacksOnStacks.cfg#L14 Guess the mod does not follow the config.

**Comment by Dominance** [comment]
Fixed in 1.2.7 should be released soon (within 8 hours). Removes the dust stacking mechanic all together. Thanks for the reports PaladinOne
