### ISSUE TITLE
Loot Bags give Blank Chromaticraft Info Fragments

### ISSUE THREAD

**Issue by PaladinOne** [Beyond-Reality/Beyond-Reality-Divergence#228]
Since the last pack update, I have opened many loot bags, and acquired 6 Chromaticraft Info Fragments. All of them have been Blank. I also found one Blank fragment in a conventional dungeon chest. Prior to updating, I had obtained 5 Fragments the same way, containing actual information.

**Comment by Dominance** [comment]
Divergence does not alter the loot tables for dungeons. Loot bags populate from the dungeon loot tables. With that being said I am not a ChromatiCraft expert by any means. Still trying to legit get all the way through it myself. This could be intended behavior or could be a mod bug. From what I can tell this is the only config option in the pack that could relate to this issue https://github.com/Beyond-Reality/Beyond-Reality-Divergence/blob/master/config/Reika/ChromatiCraft.cfg#L17 Honestly not sure if it was adjusted from default values or not will test soon.

**Comment by b0bst3r** [comment]
This is normal.

**Comment by Dominance** [comment]
Yes I have found it to be normal mod side as well.
