### ISSUE TITLE
CTD when scanning StacksOnStacks

### ISSUE THREAD

**Issue by SkuxxDeluxe** [Beyond-Reality/Beyond-Reality-Divergence#229]
Crash log here
http://m.uploadedit.com/ba3m/1445934576401.txt

Description: CTD when scanning a StacksOnStacks stack (was Mana infused ingots) with the Thaumometer.

**Comment by Dominance** [comment]
https://github.com/Beyond-Reality/Beyond-Reality-Divergence/issues/118

Have a older issue reported to thaumcraft with similar crash reports.
