### ISSUE TITLE
quest book

### ISSUE THREAD

**Issue by hmbigburt** [Beyond-Reality/Beyond-Reality-Divergence#23]
this is a minor problem but if you loose the quest book the is currently no way to either re-make or obtain a new one

**Comment by Dominance** [comment]
There is a supply of quest books on a small book shelf in the center room. I will add a recipe for it something I overlooked!

**Comment by Dominance** [comment]
There is a recipe for it book plus string

**Comment by hmbigburt** [comment]
thanx
