### ISSUE TITLE
Add oredict to lit redstone ores

### ISSUE THREAD

**Issue by Githubaccountlol** [Beyond-Reality/Beyond-Reality-Divergence#232]
Redstone ore lights up when you hit it.  This changes the block to /1 instead of the normal /0.  If you silktouch it in this state you get the /1 block which currently does not process in anything, due to not being oredicted.

Last addition to oredict was added here
https://github.com/Beyond-Reality/Beyond-Reality-Divergence/blob/master/scripts/ReasonableRealism.zs

**Comment by Dominance** [comment]
These changes have not been published. What your asking for is fixed in the latest release.
