### ISSUE TITLE
Broken tutorial quest

### ISSUE THREAD

**Issue by rogunhqy** [Beyond-Reality/Beyond-Reality-Divergence#238]
I just started this modpack, but am already having troubles. i start the tutorial quests and imediatly have a problem, when im attempting to make tinker construct tools, i can only place the stencil table, i cant place and of the other tables. meaning i cant progress or make any other tools. i have re installed the pack, and after every update i start a new save file, but everytime it happns.

**Comment by Dominance** [comment]
Try reading the quest and reading the in game documentation. You must click on the chairs to unlock/research mods.

**Comment by rogunhqy** [comment]
it the tinkers construct stuff, why can i put down the stencil table and not the tool station and parts builder. not chairs

**Comment by Buuz135** [comment]
Read the book, it explains it all there.

**Comment by rogunhqy** [comment]
thats all well and good, but as im looking at the quest for research, tinkers construct isnt one of them. so then how do i make tools with it if i cant research it

**Comment by rogunhqy** [comment]
dont worry, i wasnt on the latest version, and after updating i now see it all works.
