### ISSUE TITLE
Broken tutorial quest

### ISSUE THREAD

**Issue by rogunhqy** [Beyond-Reality/Beyond-Reality-Divergence#239]
because he gave no info for help for someone just starting out, i will do this again, i cant make tools because i can t place the tinkers construct tool station of parts builder, i can only place stencil table. if i need to reseaqrch it as the mod maker said in the last post, then how do i do this, as i stated im just starting out and know nothing about this pack except for it being in beta

**Comment by mlard811** [comment]
This isn't an issue with the pack. You are just missing a critical step.  Go into the temple, in the center tutorial section you will find a door has opened on the left to a room with a chair in it.  Right click the chair to unlock the part builder and tool station.  (Shift-right click to get out of chair.)  When you get in the chair you'll see a notification in the upper left that you unlocked it.  This is how you unlock most things in the pack.  As you progress doors will open and you go sit in the chair to get the knowledge.

-[JiF]Mike

**Comment by Dominance** [comment]
This is the second time you have opened this issue in the same day. Read the book please its really not that hard.
