### ISSUE TITLE
Things to fix for 1.1.0

### ISSUE THREAD

**Issue by Dominance** [Beyond-Reality/Beyond-Reality-Divergence#24]
Make chairs unbreakable again
Remove telepads from TE and dislocator from Blood magic.
Work on the documentation book remove all old content and fix grammer/formatting issues.
Find a fix for Thor's hammer breaking the temple blocks.

**Comment by Dominance** [comment]
Add 1 warded glass in each room to prevent ender pearl glitch

**Comment by hmbigburt** [comment]
land generation can be a bit slow at times, lag spikes can be a bit of a pain but don't know if those are fixable
