### ISSUE TITLE
Progression Issue: AgriCraft

### ISSUE THREAD

**Issue by balderdk** [Beyond-Reality/Beyond-Reality-Divergence#242]
Hi

I dont know if this kind of issue should be discussed here instead of irc, feel free to close this if you feel it's better suited for irc :)

I have hit a snag on progressing with AgriCraft, for getting into the "usefull" tier of AgriCraft (metals) the entry seed needed is Redstrodendron you get that by breeding 2 other flowers with a vanilla redstone block under, it does not accept Harder ores by looking at nei at least.

The same is true for Diamahlia/Emeryllis seeds and all the metals, i dont see as an issue with the metals as you can make the ores using the 4 small ores on a crafting table, but 4 small redstone ores only gives 1 redstone dust, not an ore block.

I looked at Botania the Orechid can convert Stone to Ore so you could possibly get it there later on (after terra steel) but having the entry level blocked is a bit unfortunate.

Kind regards Tunnasdk

**Comment by Dominance** [comment]
Have you actually tried this or just looked at NEI? As the only one that is broken is diamond which I fixed 9 hours ago here https://github.com/Beyond-Reality/Beyond-Reality-Divergence/blob/master/scripts/agricraft.zs I appreciate the issue just try to make sure everything you report as broken is broken. Else I will waste my time trying to replicate why its not broken for me and is broken for you.

**Comment by balderdk** [comment]
As i wrote i have only looked at NEI, I'm sorry i will try and make it more clear next time i report something, ore dic support shows up for the metals but not for redstone/emerald/diamond so i though it was indeed a config issue.

**Comment by b0bst3r** [comment]
Tested redstone on 1.2.7 and it works fine, then noticed you updated so will try that.

When I say tested I:

Silk touched some harder redstone ore and used that block to grow under the plants if it doesn't like the block it lets you know in waila pretty much straight away.

Works on mutation and general growing.

**Comment by Dominance** [comment]
Diamonds working good in 1.2.7.1 Cheers
