### ISSUE TITLE
Pams and cooking problems

### ISSUE THREAD

**Issue by mrbaggins** [Beyond-Reality/Beyond-Reality-Divergence#243]
Fresh water only gives 1, not 4 like it normally would (Maybe that was deliberate?)
Fresh water is disabled for most recipes, making many much more tedious to craft, as they need buckets.
Tool racks from cooking for blockheads don't display items / utensils (stove doesn't either).

**Comment by Dominance** [comment]
1 and 2 fixed here https://github.com/Beyond-Reality/Beyond-Reality-Divergence/commit/4a7015b6394c788c030493aefe2c394d1296cf78 Sorry forgot to change the test config.
3 is a mod side issue the mod author opened up a issue on the tracker already https://github.com/blay09/CookingForBlockheads/issues/99.
http://i.imgur.com/tBAygSE.png with texture pack without texture pack http://i.imgur.com/iXCBwFr.png What you are noticing is a render/directional error from the mod itself. It does not rotate the items very well, If the blocks are not facing north the items do not render correctly on fast render works on fancy.

**Comment by Dominance** [comment]
Next version
