### ISSUE TITLE
Balance: Chisel & Chests

### ISSUE THREAD

**Issue by Saerdna256** [Beyond-Reality/Beyond-Reality-Divergence#245]
You can turn chests into Enderchests using Chisel. I can't imagine this is intended balance-wise as you seem to be trying to restrict access to (item) teleportation to end-game / expensive stuff.

And on a totally unrelated note: Thanks for this great mod-pack. I didn't have as much fun with minecraft for quite some time.

**Comment by Dominance** [comment]
Will fix asap!

**Comment by Buuz135** [comment]
Fixed
