### ISSUE TITLE
Single Player Lag badly and crash after N Minues

### ISSUE THREAD

**Issue by ghost** [Beyond-Reality/Beyond-Reality-Divergence#246]
i play mostly in single player after update for 12.7.x
i get a very lagy play thu and i mean badly (in 1.2.6.x) it was fine and fun to play
i put here 1 is full log and two crash that i give 
Description: Exception getting block type in world

java.lang.StackOverflowError: Exception getting block type in world

p.s: the crash are of different worlds
the crash logs:
http://www.pasteall.org/61951
http://www.pasteall.org/61952
full log one of the game crashed:
http://pastebin.ca/3227909

**Comment by Dominance** [comment]
Please try changing this https://github.com/Beyond-Reality/Beyond-Reality-Divergence/blob/master/config/sfartifacts.cfg#L15 to false in your SF artifact configs. Or zip your world so I can attempt to replicate ths issue. Its not the first I have seen this happen. I just have never had it happen to me.

**Comment by ghost** [comment]
https://mega.nz/#!KkhRiBIY
it my save directory hope it help

**Comment by Dominance** [comment]
Need the key

**Comment by ghost** [comment]
sorry about at didnt know it lock the file 
found the key is : 
!cSn_m2wFL3GowFbV3U-Z9PzaAyndOr71z3BSkS8iQ_4

**Comment by ghost** [comment]
please let me know if working or have issues with the files
