### ISSUE TITLE
Balance AgriCraft

### ISSUE THREAD

**Issue by Dominance** [Beyond-Reality/Beyond-Reality-Divergence#247]
# End goal is to make agricraft as balanced as bees.

**There should never be a clear winner with two mods that achieve the same results. One may always have the edge over another. How ever the player should not feel gimped for using the harder method .If you disagree with this go bitch elsewhere and stop playing Divergence. With that being said if you have any suggestions for the next update that will acomplish this goal please chime in.**

As to why it was not done before it was added. This pack is in beta and will remain there until all major changes like this are complete. Also instead of postponing the latest update I decided to proceed with adding until I had more time to adjust it and feedback to go by to balance it.
- Add in all crops that do not exist currently for existing ores.
- Disable Clipper
- Lower % chance for crops to mutate. Currently **S:"Mutation Chance"=0.2** change to  **S:"Mutation Chance"=0.1**
- Cap top level of crops to 5
- Make a custom block that requires a admirable amplification in the recipe. To be used under every resrouce type plant IE **Redstone, Iron or gold**
- Remove the ability to use bonemeal on plants.
- Lower chance of spreading by a small margin.
- Lower growth multiplyer Currently **Growth rate multiplier=0.7** change to something like **Growth rate multiplier"=0.4**

**Comment by mrbaggins** [comment]
> Make a custom block that requires a admirable amplification in the recipe. To be used under every resrouce type plant IE Redstone, Iron or gold

If you're going that way, I'd maybe suggest doing it in tiers. Make iron and copper require the first one, tin, redstone and silver the second, ferrous and gold the third etc.

You can do the crops completely individually, setting say redstone to spread much more than iron, or or giving individual mutations higher or lower odds. You can also do the parents in the config file too.

**Comment by Githubaccountlol** [comment]
I think making the mutation rate lower is a terrible idea.  It adds even more mostly-afk waiting time to an already afk-waiting heavy pack.  It does not require any skill or decision making from the player, only a further increased tolerance for frustration and boredom.  Click, wait, click, wait.  Turning that into click, wait, click, wait, click, wait, click, wait, click, wait does not improve anything.

Custom bottom layers is a much better idea, as you're requring an active choice as to what level of investment the player wants to make, and ties in the other resource processing/automation methods.  I just don't know what the right costs would be as you will need several to even do the breeding.  I agree with the tiering idea, but if possible make the higher tiers work for lower plants as well. If agricraft supports oredictionary for the bottom layer that would be straightforward.

**Comment by tentonaxe** [comment]
It's a difficult thing to balance when you consider the fact that agricraft also gives food, where as bees do not. If you then include all of forestry in the comparison, you have to include tree breeding, which can be very powerful once the biomass issue is resolved.

But I don't like "time" being what makes a mod difficult, difficulty should instead be complexity or resource needs. I like the idea of balancing it by changing the bottom layer blocks, just not the changes to growth/mutation speeds. Bees can be made to be fast too, the only difference being they take more space/power and are more complex. Just cap the level to 5 like you did and change the bottom layer.

**Comment by balderdk** [comment]
Having played with the current level of mutation, going from lapis to diamond literately took me under 2 minutes, add Lamp of Growth from Thaumcraft + Sprinklers from AgriCraft and they mutate right away.

**Comment by Belgabor** [comment]
I agree with what people said about base blocks being the better idea vs. nerfing growth/mutation chances. But I also disagree with capping the stats. Lower top stats just mean you have to grow more leading to more lag all around, imo it doesn't solve anything.

**Comment by bengalgod** [comment]
Balance must be sought carefully. Overbalancing in favor of bees is just going to anger people and leave you with more work to do later if you still want balance. Gradual steps are superior to sweeping changes.

**Comment by choum33** [comment]
Hi,

Yes agricraft is overpowered. For me the main thing is that plants drop too much goods. An idea for exemple would be to drop 1 tiny pile of redstone dust rather than 1 redstone dust, or even less, the same for other ressources exept wheat maybe. Or get fruits that must be processed like combs but here i think it's more a job for the mod developper ;)
