### ISSUE TITLE
Not sure if bug or deliberate: Biomass WAY under normal power

### ISSUE THREAD

**Issue by mrbaggins** [Beyond-Reality/Beyond-Reality-Divergence#248]
_Summary: Not sure if bug or super nerfed:_
Fermenter running at 20% biomass generation instead of 50% (or higher if Forestry isn't supposed to be on HARD mode).
Still running at 260% power consumption (160rf/t instead of 60)
Fermenter running at 300% power consumption (480 instead of 170)

_Details_
So I figured my stirlings were pretty poor, and rigged up a tree farm for making biomass.

Vanilla oak saplings and their forestry equivalent "Apple oak saplings" normally give 250mb of biomass in a fermenter. Even on Forestry= HARD mode, they should be penalised by 50%.

However an apple oak sapling is giving me only 50mb each.
Likewise, a balsa sapling is giving 100mb (instead of 500).

That's an 80% penalty.

The end results of this is that if I start with 10 buckets of biomass, use that to run a generator, to run a fermenter to make more biomass, I'll burn 128 saplings and end up with only 6.25 buckets of biomass. IE: It can't even power itself, assuming infinite saplings and fertliser.

Using a tier 2 sapling like balsa will end up with 10 buckets and 128 saplings making 12.5 buckets, so able to make a profit if you're willing to create a HEAP of tree farms.

What this amounts to, are biogas engines supposed to be nerfed out of early / mid game this far? 20% effectiveness pretty much means their useless until you've bred a much better fuel tree. Which is fine if true, but a warning on that would be nice.

Even using a higher sappiness sapling, the net profit is so low as to make this useless compared to other power generation uses. You're better off in most cases using the saplings as the fuel for burning wood into charcoal.

Edit: The still is no better, or has been nerfed into oblivion as well. Forestry site says a still uses 6Mj/t max, (60RF) but in practice it needs 160RF. This means that you need 4 combustion engines just to run a still. Which is pointless, as 4 combustion engines using 1 bucket of ethanol each will make about 4.5 buckets of ethanol. So for a massive infrastructure cost you get about 20rf/t

**Comment by Dominance** [comment]
Foresty configs other than switching it to hardmode are all default generated. I will look into this how ever. Most likley this will be fixed when we move to forestry 4. Ether will fix by next update or will update forestry 4 to fix by next update. Which ever comes first.
