### ISSUE TITLE
Compacting drawer eating materials

### ISSUE THREAD

**Issue by tentonaxe** [Beyond-Reality/Beyond-Reality-Divergence#249]
When i put more than 336 blocks if ingots into a compacting drawer, the items disappear. :(

Tested with both ferrous and iron.

**Comment by Dominance** [comment]
Easy way for me to fix this and the most likley will be to just remove the compacting drawer. As the compacter from bdew has the same function. As there is no config option I know of that I can work with on my side. Other than that we would have to toss @jaquadro a issue on the mods tracker and wait for a update.

**Comment by jaquadro** [comment]
Need more information.  Compacting drawer should never eat material, unless there is a specific mod interaction at fault.

**Comment by Belgabor** [comment]
I suspect whatever mod reduces the stack size is at fault...

**Comment by Belgabor** [comment]
Also the compacter does NOT have the same functionality, it doesn't seem to understand oredict.

**Comment by Buuz135** [comment]
Fixed
