### ISSUE TITLE
AE and Progression

### ISSUE THREAD

**Issue by Cantankerous-Rex** [Beyond-Reality/Beyond-Reality-Divergence#253]
I was wondering if for the next patch we could split AE into a basic and advanced version like some of the other mods. 

Basic would not allow you to place a controller so you would be limited in channels. This would greatly help with storage in that lots of items don't seem to stack and storage is a serious pain atm. Even using Storage Drawers and modular it is still a pain.

It would also give a taste but also give something more to aim for.

**Comment by Dominance** [comment]
Worth looking into will be merging into the proper issue
