### ISSUE TITLE
SFM

### ISSUE THREAD

**Issue by ukdunc** [Beyond-Reality/Beyond-Reality-Divergence#254]
SFM is a challenge enough as it is for a hard pack but it would allow a degree of automation if used well with the amplifications.  If combined with basic AE2 (see Rex comment) it would make the progression at least less tedious when it comes to the crafting.

**Comment by balderdk** [comment]
You can automate all rune crafting with vanilla and botania, i have that setup, personally i think SFM is very nice, but also to powerful.

**Comment by Dominance** [comment]
no not interested in adding SFM sorry :(
