### ISSUE TITLE
Railcraft - server crash

### ISSUE THREAD

**Issue by balderdk** [Beyond-Reality/Beyond-Reality-Divergence#255]
When shift clicking a Immersive Enginnering Drill into a Railcraft steel talk (with biofuel) server died with this error: http://pastebin.com/Z0wG8vdL

I will now attempt to MCedit to remove the tank and save the world, as the server continuously crashes when loading those chunks. :)

**Comment by Dominance** [comment]
Try to disable https://github.com/Beyond-Reality/Beyond-Reality-Divergence/blob/master/config/railcraft/blocks.cfg#L45 and see if the server will boot. Afterwords you may need to reinstall the progression config folder.

**Comment by balderdk** [comment]
I'm good i just used mcedit to remove the bottom center block in the tank that stores the entity data.
