### ISSUE TITLE
Aluminum Ore?

### ISSUE THREAD

**Issue by Leftorius** [Beyond-Reality/Beyond-Reality-Divergence#258]
Seems that after looking for more than 10 hours I can't find any Alumin Ore even with a dowsing rod for test purpose. I used every Information I could but still dont know. Is the flower correct spawning of it?

**Comment by Belgabor** [comment]
We had the very same issue. We made do until we had the IE excavator, never found any harder ores aluminium.

**Comment by vagaprime** [comment]
Best bet look for hardened clay despots. The hard Aluminium ore will spawn in them.

**Comment by Dominance** [comment]
Its correct and does spawn. It is how ever one of the few ores that only spawn in the designated biomes.

**Comment by Leftorius** [comment]
yeah no chance, I can only find apatite in swamps, I dont find any mesa biomes, looking for 3 days now I yeah just frustating that I don't have any other chance except from lootbags to get aluminum :/ 

Or is it not wise to use ATG ? Because that could explain that... :/

EDIT2: created a new world and found aluminum after serveral minutes BUT the dowsing rod isn't working on hard aluminum ore so that could be a possible error too and the flowers doesn't spawn for them, so 2 issues who makes to find those ores almost impossible on ATG :I 

EDIT3: so deleted all dirt/stone/shit on 3 swamp biomes I found with ATG, there is an error with that world gen, it doesn't spawn aluminum? and the problem is, those biomes on ATG are really small and yeah :( so I have to start a new map

**Comment by Dominance** [comment]
While I know for sure ATG world type does spawn aluminum. It does seem to mess up a lot more than its worth. Think I will be removing it next version.

**Comment by vagaprime** [comment]
That is odd. I have found the hard Aluminum in plains biomes before. I have found that Iron is hard to find for me.

**Comment by Leftorius** [comment]
So I decided to start over, it's too bad but still in beta so yeah :D now just with the normal MC gen..
