### ISSUE TITLE
Cooking for Blockheads fridge doesn't stop food spoiling

### ISSUE THREAD

**Issue by Belgabor** [Beyond-Reality/Beyond-Reality-Divergence#259]
The changelog says "The freezer from Cooking with blockheads works to stop food rotting.", that doesn't work. Put in biscuits of totality, came back later, only rotten food left.

**Comment by Dominance** [comment]
https://github.com/Beyond-Reality/Beyond-Reality-Divergence/blob/master/config/cookingbook.cfg#L65 Is enabled in the change logs I how ever did not describe it as it should of been as I was under the assumption that it worked the way I described. This is the true way https://github.com/blay09/CookingForBlockheads/commit/ad1a8a13f76e3ed22bd37e7ef9afabd8def27ae5
