### ISSUE TITLE
hardcore questing mode

### ISSUE THREAD

**Issue by hmbigburt** [Beyond-Reality/Beyond-Reality-Divergence#26]
when i go to use the book for the glass bottle level all it gives me is a msg that i need to do 
/hqm quest to activate, havent got a clue why, here is a screen shot of the msg. 
https://gyazo.com/11eb91ed4b8ab0998b9b44d67c375121

**Comment by Dominance** [comment]
Just do /hqm quest in chat

**Comment by hmbigburt** [comment]
it says "you don't have permission"
