### ISSUE TITLE
Growthcraft cider

### ISSUE THREAD

**Issue by vagaprime** [Beyond-Reality/Beyond-Reality-Divergence#260]
SO I tried to make some of the growth-craft cider a couple days ago and the fruit press does not seen to recognize the apples once the decay timer starts on them. Which means that I am unable to make any of the cider.

**Comment by Belgabor** [comment]
That's part of growthcraft-apples, which is not in the pack.

**Comment by vagaprime** [comment]
Ah. Ok.
