### ISSUE TITLE
Request making Cryanos Lootable bodies mod optional on client install.

### ISSUE THREAD

**Issue by Yorkforce** [Beyond-Reality/Beyond-Reality-Divergence#261]
Unfortunately this mod causes a client crash on servers due to the ai range issue
http://pastebin.com/ciezR8Km

Any chance it can be moved to the optional side for client installs, its saves us having to tell players to disable the mod due to the crash and also matches the server installs optional selections too.

**Comment by Dominance** [comment]
Its going to be replaced/removed next version.

**Comment by Dominance** [comment]
Dropping it next version thanks.
