### ISSUE TITLE
Furnace is locked behind Early Game Tech and AE

### ISSUE THREAD

**Issue by Yorkforce** [Beyond-Reality/Beyond-Reality-Divergence#262]
The furnace your given as a reward (vanilla ID61) says its Locked and requires Early Game Tech and AE to use.

The slab furnace works fine, there is also another furnace listed (ID62) that isn't locked but also isn't craftable.

This is for version BR: Divergence 1.2.7.1

**Comment by Dominance** [comment]
Reinstall your config folder. Ether you disabled some mods or you some how have a bad json

**Comment by Yorkforce** [comment]
We disabled Harder Wildlife due to the tick rate issues, would that cause this issue?
