### ISSUE TITLE
custom ore generation

### ISSUE THREAD

**Issue by hmbigburt** [Beyond-Reality/Beyond-Reality-Divergence#27]
when using the custom ore generation option when creating a new world in sp the game returns me to the launcher just before the end of generating the map,
https://gyazo.com/8aab82da702ca565a6087b2c12bd2b11

**Comment by Dominance** [comment]
Yeah. When I did it all myself I just disabled all the options. How ever reasonable realism adds in its own custom ore gen files and the sliders and options are there. The ore gen is not meant to be adjusted in the pack so leave it as default. I will be tossing in a notification soon that explains this before you get to the main menu. But yeah for now just dont adjust anything.

**Comment by Dominance** [comment]
Got the Launch message up to handle this issue if it ever comes out again. Thanks for the report bro!
