### ISSUE TITLE
Possible incompatibility between Hardcore Wither and Runic Dungeons

### ISSUE THREAD

**Issue by Belgabor** [Beyond-Reality/Beyond-Reality-Divergence#270]
I can't be 100% sure on this, but there seems to be an issue. I fought 4 withers fine in the runic dungeon, now the fifth always spawns unreachable above the dungeon roof. I can only assume that this is an effect of Hardcore Wither difficulty progression...

**Comment by thor12022** [comment]
Likely the Wither teleported above the dungeon roof. I didn't take enclosed dungeons in the void into account. . . 

I came here to say that you could disable the Teleport ability in the configs, but inspection has revealed that I've managed to fail at making some things configurable. I created an [issue](https://gitlab.com/thor12022/HardcoreWither/issues/29) to fix that in the next release.

Ideally I'll have some way to identify Runic Dungeons Withers and ignore them, but that's probably Future Thor's problem.
