### ISSUE TITLE
Crash to Desktop with Throwing Knives

### ISSUE THREAD

**Issue by MightyCalt** [Beyond-Reality/Beyond-Reality-Divergence#271]
When I break an object with left-click while holding my flint throwing knives the game crashes. Survival Single Player. Happened with grass and a torch. Most recent crash log attached.
[crash-2015-11-23_21.10.56-server.txt](https://github.com/Beyond-Reality/Beyond-Reality-Divergence/files/42385/crash-2015-11-23_21.10.56-server.txt)

**Comment by Buuz135** [comment]
Fixed
