### ISSUE TITLE
No recipe for tech augmentations in NEI (Divergence 1.2.7.1 beta)

### ISSUE THREAD

**Issue by FrancisDrake88** [Beyond-Reality/Beyond-Reality-Divergence#274]
Wicked pack, love beyond reality and the added quest system in divergence is sick. But I can't progress as I don't have a recipe for the tech augmentations. I found videos on youtube of people making them and tried the same recipes thinking that maybe they just don't show up, but I can't craft them like they did. I am playing the latest release on atlauncher on a server made through atlauncher. Thanks for your hard work on the pack.
Regards
Francis88

**Comment by Belgabor** [comment]
Did you forget to select a difficulty rating when downloading the pack?

**Comment by FrancisDrake88** [comment]
Possibly, I'll try that and check. I'll let you know later today if that
was it. Thanks for the fast reply.

**Comment by FrancisDrake88** [comment]
Sick, that did it. I selected the hardcore with the optional darkness only. When I selected hardcore default and the darkcore with darkness it worked. Thanks for your help.
