### ISSUE TITLE
Thaumcraft Treasure Bags

### ISSUE THREAD

**Issue by Yakumo257** [Beyond-Reality/Beyond-Reality-Divergence#276]
For some reason I'm unable to open any of the Thaumcraft treasure bags, common or uncommon save for one. I thought I had to unlock the Thaumcraft branch first in order to actually interact with them but even after doing so they still won't do anything on right click. Not sure if it's on my end or what.

**Comment by Leftorius** [comment]
I think you can only trade with them. You won't be able to open them.

**Comment by Yakumo257** [comment]
Well with one I was able to open and got a few gold coins, just unsure why
the others aren't opening. But I'll save them for trading.
