### ISSUE TITLE
Tinker's Construct Smelteries

### ISSUE THREAD

**Issue by nwmqpa** [Beyond-Reality/Beyond-Reality-Divergence#278]
After pushing a friend into a smeltery for him to die , a skeleton from Lootables Bodies appear , and it startes boiling with the other liquids . We figured out that the corpse , wich has infinite live , deliver infinite blood also

**Comment by spacebuilder2020** [comment]
xD

**Comment by Bewilderer** [comment]
Until it despawns :(

**Comment by Buuz135** [comment]
That's an old Tinker's issue that probably the won't fix
