### ISSUE TITLE
Container type Sluice

### ISSUE THREAD

**Issue by postal291** [Beyond-Reality/Beyond-Reality-Divergence#280]
Everything I've read said it needs to be underneath running water, but if water touches it, it breaks.  Can't figure out how to use this thing...  At least the mill works.

**Comment by RayMarDesign** [comment]
The water needs to reach its limit above and behind the sluice, not directly above it. You can confirm it works by having a block clear below and in front of the sluice. It will place a water block there if it is fed water correctly.

**Comment by postal291** [comment]
You have to leave a block open below it?  That might have been the problem.
Thanks Ray

**Comment by RaineAndrews** [comment]
I have issues with this too.  The book should definitely be updated with the container sluice info.

**Comment by Buuz135** [comment]
This is how it works: http://i.imgur.com/zi5zlIn.jpg

New book coming soon :tm:
