### ISSUE TITLE
Pack abandoned?

### ISSUE THREAD

**Issue by mrbaggins** [Beyond-Reality/Beyond-Reality-Divergence#281]
Just wondering what's going on? Hasn't been an update in a long time and I'm not seeing a lot (any?) Activity on issues. No info either, and several mods have made some big fixes that would be good to see

**Comment by Dominance** [comment]
Awaiting Binnies to update. If it does not update by 1/8/2016 I will be dropping it so I can start updating. Now days mods are interconnected and when one is dependent on a certain version of a certain mod it can as in this case spread like wildfire. Just as a example. Forestry 4 is required by mod X and mod Y requires a updated version of mod X which is dependent on forestry 4 while mod Z requires mod Y. That is basically where we are today.

**Comment by mrbaggins** [comment]
No worries. Just had been quiet for a long while.

**Comment by Dominance** [comment]
Starting Updating Process no ETA but work has begun

**Comment by sapid** [comment]
A fix for Binnies compatibility with Forestry 4 is now available.
http://forum.feed-the-beast.com/threads/1-7-10-binnie-patcher.143722/

**Comment by Dominance** [comment]
Have it updated and loading. Just need to start addressing some issues that where not fixed by updating mods. And address the many issues that have arisen from updating mods.

**Comment by vagaprime** [comment]
I was wondering if it would be possible to get an update on the progress of the next pack update?

**Comment by Dominance** [comment]
Just trying to get something worked out on AT launchers side. Seems setting extra Java arguments is not working anymore. With the new chromaticraft you need a Java argument or it crashes to desktop. Rather not deal with that on a pack wide basis. So until I get it worked out not ETA.
I was wondering if it would be possible to get an update on the progress of the next pack update?

---

**Comment by vagaprime** [comment]
Thanks for the update.
