### ISSUE TITLE
Loot from living armor gives a vanilla iron sword instead of a tinkers variant

### ISSUE THREAD

**Issue by spacebuilder2020** [Beyond-Reality/Beyond-Reality-Divergence#285]
![2016-01-17_16 20 52](https://cloud.githubusercontent.com/assets/8677143/12380695/4effac98-bd36-11e5-99c2-1310c2ac3cf3.png)

This is annoying as you can see in the picture cause the sword has sharpness 3 and soul eater 4.  There is no way to get these enchantments on a sword that will last more than one shot.

**Comment by Bewilderer** [comment]
Couldn't you use a mana enchanter to acheive the same effect on a regular sword?

**Comment by Bewilderer** [comment]
I.E., a usable TiC Sword

**Comment by vagaprime** [comment]
Only way to add an enchant to tcon weapon that I know of is by using an enchanted book and anvil.

**Comment by spacebuilder2020** [comment]
Meta data from tinkers tools is very complex.  I gave up trying making a kit for new players cause the meta data was too complex.

**Comment by Buuz135** [comment]
"Intended"

**Comment by spacebuilder2020** [comment]
Basically due to iguana tweaks it results in useless loot that might as well be removed. Cause what can you do with a tool with 1 durability point.  You can't even get all the enchantments of it cause it will break the first time.
