### ISSUE TITLE
Unstable cobble not smeltable in smeltery (And other cobble related bugs)

### ISSUE THREAD

**Issue by spacebuilder2020** [Beyond-Reality/Beyond-Reality-Divergence#286]
You can only use normal cobble in the smeltery.
![2016-01-17_16 39 36](https://cloud.githubusercontent.com/assets/8677143/12380812/f6bcea48-bd38-11e5-96c6-0dc5ce68ffae.png)

![2016-01-17_16 39 58](https://cloud.githubusercontent.com/assets/8677143/12380817/fb490d76-bd38-11e5-9d18-1a296eef0fa2.png)

Also, you can get normal cobble from a cobble gen as well a chisel (from unstable)

Finally, cobble still spawns in the world with villages and a few patches related to chromacraft.

**Comment by spacebuilder2020** [comment]
![2016-01-17_20 27 36](https://cloud.githubusercontent.com/assets/8677143/12382588/d597f612-bd58-11e5-93ca-6d361a2a574a.png)

**Comment by Dominance** [comment]
Yeah would take far to much time to fix this. I would list this as unfortunate working but not as intended.

**Comment by spacebuilder2020** [comment]
ok
