### ISSUE TITLE
Tech Augment recipe won't show up.

### ISSUE THREAD

**Issue by aad74** [Beyond-Reality/Beyond-Reality-Divergence#288]
I have completed the BuildCraft task that required 20 ingots and it shows as complete in my quest book but to move on any further in the quest book I need to craft tech augments but the recipe will not show up. I have shut down and restarted but that didn't help. I visited the room with the spanner on the door and have sat on the seat several time hoping that would help unlock the recipe but sadly it didn't. The next step is to reinstall the pack but I would rater not if there is a simple solution.

Also on a side note I can't open the treasure bags. I have no issue with the loot bags just the treasure. Are these only for trading or should they open ?

**Comment by b0bst3r** [comment]
Run a /mt reload

**Comment by aad74** [comment]
Reinstalled pack and it's now working.
