### ISSUE TITLE
Please update SkinPort to latest version.

### ISSUE THREAD

**Issue by zlainsama** [Beyond-Reality/Beyond-Reality-Divergence#29]
Since 1.7.10-v2, some issues has been addressed and fixed:

1.7.10-v3: fixed skin unloads itself from time to time, even when you are look at them. (they will unload if they are not being rendered)
1.7.10-v3a: skins will stay loaded when those players are still in your client world. (even if they are not being rendered)
1.7.10-v3b: it's now compatible with java 1.7.
1.7.10-v3d: fixed first person hand rendering looks weird when another player with same model is riding an entity. (its a vanilla graphic bug: https://bugs.mojang.com/browse/MC-1349)
1.7.10-v4: ensure compatibility with SmartMoving and RenderPlayerAPI.

Current latest version is 1.7.10-v4.
It's nothing serious though.

**Comment by Dominance** [comment]
Got it updated Thanks Zlainsama! Also thanks for the amazing mod! Version 1.1.5-1.1.6 should have the newest release

**Comment by zlainsama** [comment]
Thanks. You are welcome :)
