### ISSUE TITLE
Thaumcraft locked under Agricraft

### ISSUE THREAD

**Issue by Kerydwenn** [Beyond-Reality/Beyond-Reality-Divergence#291]
Hi,

After unlocking Thaumcraft, we noticed it was impossible to open the Thaumonomicon, as it is labelled as "Currently Locked - Requires Agricraft". We noticed this issue on 2 items so far: the Thaumonomicon and Thaumometer. Not sure about any other items yet, so far only these two seem to be affected. The Locked status appears both in the NEI and on the actual Thaumonomicon--which I got from a chest, no crafting involved.

This seems weird and illogical, since TC is definitely Tier 1, and doesn't seem to depend on anything else than Botania, which we have unlocked. This according to the tree in the Quest book, at the least.

We're on Divergence 1.2.7.1. We have unlocked TC by crafting the 30 needed Notable Magic Amplifiers, by validating the quest in the book, and by sitting in the TC chair in the temple. Nothing missing here as far as I can tell. 

Is this a bug? The only other explanation I can imagine is needing to actually craft the Thaumonomicon instead of using one I found, and then discover its research; however, this still doesn't account for the "Requires Agricraft" tag.

Cheers,

K.

**Comment by Kerydwenn** [comment]
Addendum: When I look up the Thaumonomicon recipe in NEI, it appears as unlocked, stating I need to click the chair. Not sure where to go from there.

**Comment by choum33** [comment]
i noticed same issue on many servers so it should be a modpack issue here :(

**Comment by Dominance** [comment]
Will be fixed next update asap.

**Comment by Kerydwenn** [comment]
Thank you! :)

**Comment by Bewilderer** [comment]
You can still access  the thaumnomicon through Enchidrion :3

**Comment by sapid** [comment]
For those looking for it, the fix is in https://github.com/Beyond-Reality/Beyond-Reality-Divergence/commit/8489e18cab5f5072cbd29c8a67cd878145c17f57 I believe.

**Comment by Kerydwenn** [comment]
Confirming the fix works. However, if players have already unlocked Thaumcraft, they'll also need to have their player profile (including achievements) reset, otherwise TC remains locked under... TC. (This seems to be related to the Progression mod.)

**Comment by Dominance** [comment]
Fixed in 1.2.8
