### ISSUE TITLE
Matter Overdrive issues

### ISSUE THREAD

**Issue by RedTheChangeling** [Beyond-Reality/Beyond-Reality-Divergence#292]
would it be possible to remove matter overdrive? it seems to slow my game down quite a bit and seems to be the cause of my game not responding for extended periods of time.

(most common message on the console: [pool-3-thread-1/ERROR] [Matter Overdrive]: There was a problem getting a Matter Entry)

**Comment by choum33** [comment]
upgrade matter overdrive solved al lthe issue for me ;)

**Comment by Dominance** [comment]
WIll be good to go next update coming soonish.

**Comment by choum33** [comment]
Hi Dominance! ;)
any idea when?
Is it possible to include hexcraft and immersive engineering update too please? ;)

**Comment by Dominance** [comment]
Yup troughs and over 60 mods updates. Had a list but was lost in transition.

**Comment by choum33** [comment]
Hi Dominance,
If you need some help just kick me ;)i know that the binnies update is a pain now, i found an unofficial patcher that seem to works on my divergence server, but as i had to update forge i'll have to update all mods and i think it's a little stupid to make the same job many times LOL
[1.7.10] Binnie Patcher

|   |
|   |  |   |   |   |   |   |
| [1.7.10] Binnie PatcherWith Binnie's normal incredibly slow update cycle lagging considerably behind that of Forestry's, I got bored waiting for the next version to... |
|  |
| Afficher sur forum.feed-the-b... | Aperçu par Yahoo |
|  |
|   |

I'm sure to not be as skilled as you, but if i can help it will be with pleasure ;)
My best regards
CHOUM33

```
  De : Dominance <notifications@github.com>
```

 À : Beyond-Reality/Beyond-Reality-Divergence Beyond-Reality-Divergence@noreply.github.com 
Cc : choum33 choum33@yahoo.fr
 Envoyé le : Lundi 15 février 2016 3h22
 Objet : Re: [Beyond-Reality-Divergence] Matter Overdrive issues (#292)

Yup troughs and over 60 mods updates. Had a list but was lost in transition. —

**Comment by Dominance** [comment]
Yeah I am just trying to get the time to finish things up. The newest dev build has everything updated already. Give me your in game name and I will add you too dev builds ASAP.

**Comment by choum33** [comment]
Great ;)my game name : choum33i'll need the link to get the pack too ;)
My best regards

```
  De : Dominance <notifications@github.com>
```

 À : Beyond-Reality/Beyond-Reality-Divergence Beyond-Reality-Divergence@noreply.github.com 
Cc : choum33 choum33@yahoo.fr
 Envoyé le : Mardi 23 février 2016 23h13
 Objet : Re: [Beyond-Reality-Divergence] Matter Overdrive issues (#292)

Yeah I am just trying to get the time to finish things up. The newest dev build has everything updated already. Give me your in game name and I will add you too dev builds ASAP.

**Comment by Dominance** [comment]
Stuff should work now with 1.2.8 if not I will try to get to these issues a bit faster.
