### ISSUE TITLE
Crash around small dungeons.

### ISSUE THREAD

**Issue by Pyriana** [Beyond-Reality/Beyond-Reality-Divergence#295]
This is the second crash I've had around small dungeons (3x3 structure above ground) in my week of playing on a server my friend set up.

The only fix so far has been teleporting me away from it.

[crash-2016-02-07_20.13.25-client.txt](https://github.com/Beyond-Reality/Beyond-Reality-Divergence/files/121129/crash-2016-02-07_20.13.25-client.txt)

**Comment by Buuz135** [comment]
Fixed, I think :stuck_out_tongue:
