### ISSUE TITLE
divergence beyond realety server not running on mac

### ISSUE THREAD

**Issue by wild11112** [Beyond-Reality/Beyond-Reality-Divergence#297]
hi im trying to set up a beyond realities divergence server on a mac computer. i have downloaded the server files and done evrything shown on this post https://forums.atlauncher.com/thread-8631.html. but it's not creating eula.txt file. here is what the launchserver.comand file comes back with whenever i try to run it. http://pastebin.com/7bXj2FeM

**Comment by Dominance** [comment]
I am not sure and unable to test this without a mac. Sorry :(
