### ISSUE TITLE
ROTARYCRAFT Extractor doesn't work

### ISSUE THREAD

**Issue by choum33** [Beyond-Reality/Beyond-Reality-Divergence#299]
Hello,

I just unblocked rotarycraft quest and crafted first machines. All seem ok but not extractor that just process nothing. I tryed vanilla iron and hard iron, and many other ores and processing just not start. I have enough power and torque for phase 1. (multiplayer server)
I tryed a creative sologame with last rotarycraft mod and dragonAPI with same result. Even with creative coil that supply enough power for the 4 process stages.
I quickly checked scripts and found nothing that disable extractor receipes.

EDIT: It works fine in the grinder, and no errors in the server log for extractor initialization.

If i can supply more info to troubleshoot just ask me ;)

Thanks

**Comment by Dominance** [comment]
Might be fixed in 1.2.8 not sure

**Comment by b0bst3r** [comment]
Old version the extractor needs a drill part inserting into the GUI for the first stage (iron or steel drill if I remember correctly).

**Comment by b0bst3r** [comment]
And yeah Dom it will be fixed in 1.2.8 because you upd Rotarycraft which removed the need for the drill bit.
