### ISSUE TITLE
Issues with hydration mechanic

### ISSUE THREAD

**Issue by Z3r0c00lz** [Beyond-Reality/Beyond-Reality-Divergence#3]
So I'm not sure if this is just a rendering issue or what, but when trying to drink the water from the cup or canteen it just moves back and forth as if my hydration is full. I periodically can drink the water so I assume that it is just a GUI rendering issue. but it shows I'm missing 3 and a half water droplets and will not let me drink from the cup or the canteen also spawned in clean water same issue.

**Comment by Z3r0c00lz** [comment]
Well it seems to be resolved now, I'll re open if I can figure out what is causing it.

**Comment by Dominance** [comment]
Ok thanks A lot !
