### ISSUE TITLE
Mouse pointer disappear because of DragonAPI update notifications

### ISSUE THREAD

**Issue by leagris** [Beyond-Reality/Beyond-Reality-Divergence#302]
The problem is caused by update notifications of DragonAPI mods that appears at the top-left when the game starts.

Relate to: https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/317
#### Fix:

Disable the notifications.
##### In-game console

``` ocaml
/checker disable [ModName]
```
##### /config/Reika/DragonAPI.cfg

``` YAML
"control setup" {
    B:"Only show update notice to Ops or SSP"=true
    B:"Only show update notice to pack creator"=true
}
```

**Comment by ghost** [comment]
Getting the same issues on Mac and Windows, however it makes playing on a Mac unplayable

**Comment by Dominance** [comment]
The message tells you to hold CTRL to be able to click the X. Have you all tried that?

**Comment by ReikaKalseki** [comment]
This was fixed months ago in v10. Why are you still on v9?

**Comment by Dominance** [comment]
Its been updated since before you posted to latest. Binnie's patcher was just released and it took a bit longer to get the pack back up to date and working after not having a release waiting on Binnie's (which was accomplished by a 3rd party) to get into forestry 4 territory.
