### ISSUE TITLE
Erroring Engine State 1.2.8

### ISSUE THREAD

**Issue by vagaprime** [Beyond-Reality/Beyond-Reality-Divergence#304]
Just updated to 1.2.8 and every time I try to load up a world or create a new world game sends me back to the main menu.

http://paste.atlauncher.com/view/7f4d33ed

From what I could trouble shoot on my end it looks like the problem lies with NEresources, as well as some possible issues in the forestry Config

**Comment by b0bst3r** [comment]
Yeah looks like this version of not enough resources is not Forestry 4 compatible

[03:30:29] [Server thread/ERROR] [FML/]: The following problems were captured during this phase
[03:30:29] [Server thread/ERROR] [FML/]: Caught exception from neresources
java.lang.NoClassDefFoundError: forestry/core/config/ForestryBlock
    at neresources.compatibility.forestry.ForestryCompat.registerOres(ForestryCompat.java:27) ~[ForestryCompat.class:?]
    at neresources.compatibility.forestry.ForestryCompat.init(ForestryCompat.java:22) ~[ForestryCompat.class:?]

**Comment by b0bst3r** [comment]
I use NotEnoughResources-1.7.10-0.1.0-122.jar with Forestry 4 and seems to work just fine, so needs an update me thinks.

**Comment by Dominance** [comment]
Thanks for the heads up. b0bstr you know I am always looking for help. Now days more so than ever. Been busy as of late.

**Comment by vagaprime** [comment]
Also I have to remove Eleccore and its mod just to log into a world. It was causing a crash to desktop.

**Comment by b0bst3r** [comment]
Make sure you use ATG to gen the world or you'll get that eleccore crash - no idea why.

**Comment by Buuz135** [comment]
Fixed!
