### ISSUE TITLE
Help offer

### ISSUE THREAD

**Issue by vagaprime** [Beyond-Reality/Beyond-Reality-Divergence#309]
Hey dom. Have you thought about adding the other modded ores to the IE excavator? If you do I can help you write up the scripts to do so. I already have a mt script that adds the infused stone that I am using in my own pack that I can send.

**Comment by Dominance** [comment]
Well I would not want all ores added. How ever I originally going to add raw ores. The tool how ever was not available up until this update.

**Comment by vagaprime** [comment]
IE has had MT support for the excavator for a while now. and I can understand not wanting to add all the ores in. The trick would be removing the current vains so that you can re add them to give you the hard ore block instead of the compressed hard ore Be warned I am not sure if it has been fixed yet but Blu told me before that the IE pages on the MT wiki are not correct in their wording.

**Comment by vagaprime** [comment]
Oh Dominance on a side note to the adding or redoing IE ore veins, The change will require, new chunks, or a new world before they will be seen.

**Comment by Buuz135** [comment]
Hey @vagaprime if you want to help, go for it, just PR stuff
