### ISSUE TITLE
Starting new world "crashes"

### ISSUE THREAD

**Issue by ghost** [Beyond-Reality/Beyond-Reality-Divergence#315]
When starting a world no matter what kind of world type i choose the world opens the "loading world" screen, and after that it just goes back to the opening screen where i can choose single player, multiplayer, and all that. I can't post a crash report because there is none! anybody have an idea what happened here? Edit: I restarted the game and launcher, now it's giving me a crash report, it says its something to do with eleccore
[crash-2016-03-18_20.38.38-server.txt](https://github.com/Beyond-Reality/Beyond-Reality-Divergence/files/180576/crash-2016-03-18_20.38.38-server.txt)

**Comment by vagaprime** [comment]
I have been having the same issue. I was able to fix it by removing Eleccore, and CMIP. You have to remove the second mod since Eleccore is needed for it to work.

**Comment by ghost** [comment]
I removed those two mods and now it wont even create a new world, im already sick and tired of it and i haven't even gotten to play

**Comment by vagaprime** [comment]
Only other option I can suggest is to also remove Not Enough Resources. If that does not work post the new crash log.

**Comment by Buuz135** [comment]
Thanks @vagaprime for all the help in the duplicated issues

**Comment by vagaprime** [comment]
@Buuz135 Not a problem.

**Comment by CrepticMoon** [comment]
I'm assuming, as of now, there is no fix yet? I'm also having the same exact issue, and I cannot figure out why.

**Comment by Buuz135** [comment]
Remove all the mods mentioned @CrepticMoon

**Comment by fspike** [comment]
Im having the same problem. No matter what mods I use or dont use. I've tried without any optional mods except the required one.

**Comment by Medicant** [comment]
Disabling NotEnoughResources worked for me.

**Comment by Ethern8ai** [comment]
i tryed to completely redownload it and use on AT launcher with new save and even removing all elecraft n cmip mods it keeps not working :s

**Comment by Buuz135** [comment]
Maybe it's because there is more to it that it's mentioned in the issue? Remove NotEnoughResources too

**Comment by Ethern8ai** [comment]
you mean not enough items? with nei integrations and all? minecraft without nei is such a pain x.x would it work to go back to the 1.2.8.0 waiting for the 1.2.8.2?

**Comment by Buuz135** [comment]
No, NotEnoughResources

**Comment by Ethern8ai** [comment]
oh méa culpa i only searched on the main mods ... Thanx for the fast awnsers, but it still dont work x.x

**Comment by Buuz135** [comment]
FIXED IN 1.2.9
