### ISSUE TITLE
Game Help

### ISSUE THREAD

**Issue by KfwPlayz** [Beyond-Reality/Beyond-Reality-Divergence#316]
When i create a world it goes to the screen that says loading world then brings me to the title screen and when I try to load it again too. It says this in the console: Server thread/ERROR] [FML]: Fatal errors were detected during the transition from AVAILABLE to SERVER_ABOUT_TO_START. Loading cannot continue. Can anyone help?

**Comment by vagaprime** [comment]
True removing Eleccore, and CMIP, ALso do you have not enough resources installed. if so try removing that one as well.
