### ISSUE TITLE
Game Crash While Loading World

### ISSUE THREAD

**Issue by Shamadruu** [Beyond-Reality/Beyond-Reality-Divergence#317]
After first creating a world in Divergence, the world does not generate and I am kicked to the main menu. When attempting to load the world, the game simply crashes. 

Crash report attached below.

[crash-2016-03-24_11.11.57-server.txt](https://github.com/Beyond-Reality/Beyond-Reality-Divergence/files/188297/crash-2016-03-24_11.11.57-server.txt)

**Comment by vagaprime** [comment]
I have been having the same issue. I was able to fix it by removing Eleccore, and CMIP

**Comment by Buuz135** [comment]
and Not enoguh resources (temp fix)
