### ISSUE TITLE
Botania quest

### ISSUE THREAD

**Issue by Rake2244** [Beyond-Reality/Beyond-Reality-Divergence#32]
As far as I can tell it's currently impossible to start Botania and thus to go down the magic questline.  I cannot make a petal apothecary nor can I turn flowers into petals, preventing me from making a mana pool to start making manasteel.  Also, the quest text says "create 10 mana infused ingots" yet the quest is asking for 20 mana infused ingots. Finally, mana infused ingots are gotten from mithril ore, which I believe isn't in world yet.  The quest should be asking for manasteel specifically.

On a side note do you want all issues here, big and small, or is there a better place for things like typos and stuff like keys still being given out with the new gate system?

**Comment by Dominance** [comment]
Big and small here is great. Infused mana Ingots are from mana infused ore. Which generates in this pack on the level 13-33 also can be found at Y level 8.

**Comment by Rake2244** [comment]
I've been strip mining a bit at level 21ish and haven't found any mana ore yet.  I'll continue that and a bit at level 8 as well.

**Comment by Towsty** [comment]
Is it supposed to be 20 or 10 ingots to complete that quest though?
