### ISSUE TITLE
Game crashes back to start after making a new world

### ISSUE THREAD

**Issue by fspike** [Beyond-Reality/Beyond-Reality-Divergence#320]
Game crashes back to main menu when I try to make a new world. 
[12/4/2016 18:59:59 PM] [Server thread/ERROR] [FML]: Fatal errors were detected during the transition from AVAILABLE to SERVER_ABOUT_TO_START. Loading cannot continue

Update: full log-http://paste.atlauncher.com/view/84cb0770

**Comment by SkuxxDeluxe** [comment]
Also having this issue.

Seems to be something to do with forestry compatibility?
Im gunna try updating forestry.

Here is my log:
http://pastebin.com/8G2p6zsU

Update: Nope, im clueless when it comes to sorting this kinda thing. Still crashes after updateing forestry. Went to the other issue and removed CIMP and eleccore or whatever.

**Comment by Nathipha** [comment]
Could it be RFTools? It showed this in the console when it crashed:
[Server thread/INFO] [mcjty.lib.varia.Logging]: RFTools: server is stopping. Shutting down gracefully
[21/4/2016 21:01:11 PM] [Server thread/INFO] [FML]: The state engine was in incorrect state ERRORED and forced into state SERVER_STOPPED. Errors may have been discarded.
[21/4/2016 21:01:11 PM] [Server thread/INFO] [FML]: The state engine was in incorrect state ERRORED and forced into state AVAILABLE. Errors may have been discarded.

**Comment by fspike** [comment]
Ive launched it a few times and RFtools isnt always the last thing before it crashes. It seems to crash at random steps.

**Comment by vagaprime** [comment]
OK there is a bug with the current version of NotEnoughResources that the pack is using that is causing this problem. Right now the best option is to remove the mod from the pack manually. That should fix the problem

**Comment by fspike** [comment]
That seemed to work thank you

**Comment by vagaprime** [comment]
Not a problem. It was one of the three mods that where giving me problems as well. and @Nathipha RF Tools always gives that message. Its the mod telling you that there was no problem that caused it to crash.

**Comment by Nathipha** [comment]
Yes, I did see the RFTools message every time and it always crashed directly afterwards for me. I disabled the 3 mods mentioned in the other thread, which fixed it.
Sadly I can't even run the modpack with steady 30fps (with Optifine! Usually I get 80-140 with a x32 texture pack.) - apparently an i7 and a GTX 770 aren't good enough for this pack.

**Comment by Buuz135** [comment]
FIXED IN 1.2.9
