### ISSUE TITLE
Singleplayer resets to main menu when loading.

### ISSUE THREAD

**Issue by DrDerpy16** [Beyond-Reality/Beyond-Reality-Divergence#324]
I cleared the logs and tried again
Upload: http://paste.atlauncher.com/view/d082e63f

**Comment by vagaprime** [comment]
dupe of https://github.com/Beyond-Reality/Beyond-Reality-Divergence/issues/320

**Comment by SkuxxDeluxe** [comment]
As with #320 , disable not enough resources.

**Comment by Buuz135** [comment]
FIXED IN 1.2.9
