### ISSUE TITLE
Unable to place furnace

### ISSUE THREAD

**Issue by fspike** [Beyond-Reality/Beyond-Reality-Divergence#325]
I cant use the furnace that comes with the first quest in the quest book. Says it requires open computers. Is this a bug or am I missing something? Im not able to get glass for water bottles...

**Comment by SkuxxDeluxe** [comment]
Yeap, ditto.
Looks like its incorrectly locked behind open computers.
Go find a village with a blacksmiths room! hehe

edit: Those furnaces dont function....

Its a trap!

**Comment by LordPinkerton** [comment]
A workaround is to go into creative mode, use /progression edit, then delete the entry for the furnace in Open Computers. If you're running a server, just replace the criteria.json file from the server with the updated one on your client, the restart the server.

**Comment by Dominance** [comment]
Yeah it's a terrible system progression has. If a mod removes / renames a item in in a update. The item once blocked by progression will revert to a furnace.
A workaround is to go into creative mode, use /progression edit, then delete the entry for the furnace in Open Computers. If you're running a server, just replace the updated criteria.json file from your system to the server's config folder area and restart the server.

---

**Comment by SkuxxDeluxe** [comment]
What a pain in the neck.

For future proofing, why not make the reward for that first tutorial quest a tinkers slab furnace?

**Comment by Dominance** [comment]
Well that would get your past that step but still breaks the rest of the game going further in. I know he's fixing it howeve
What a pain in the neck.

For future proofing, why not make the reward for that first tutorial quest a tinkers slab furnace?

---

**Comment by SkuxxDeluxe** [comment]
Ah, good point.
Hopefully he gets that fixed. Untill then, better just get into the editing!

Thanks
