### ISSUE TITLE
Borked Minetweaker.

### ISSUE THREAD

**Issue by vagaprime** [Beyond-Reality/Beyond-Reality-Divergence#326]
Ok now clue how I managed this one. Loaded up a saved game just fine. Went to create a new world and some how Minetweaker decided to error out.

http://pastebin.com/H0fyrw5M

Have fun Buuz and Dom!

**Comment by Buuz135** [comment]
Try to get the error in a new instance, I dont get the error.

**Comment by vagaprime** [comment]
Ya I reinstalled the pack and didn't seem to have the problem again. I will let you know if it decides to break on me again.

**Comment by Buuz135** [comment]
Ok cool, closing it
