### ISSUE TITLE
Game Won't startup

### ISSUE THREAD

**Issue by Syrion1** [Beyond-Reality/Beyond-Reality-Divergence#327]
After installing, reinstalling and updating, the pack crashes at the last moment at startup.
[crash-2016-04-26_10.46.27-client.txt](https://github.com/Beyond-Reality/Beyond-Reality-Divergence/files/235879/crash-2016-04-26_10.46.27-client.txt)

**Comment by LordPinkerton** [comment]
This was at the end of the latest change log.
Warning:
-Chromaticraft Crashes once at new instance/update 

After this initial crash, it should load up just fine. If the crash persists, please provide a log.

**Comment by Buuz135** [comment]
Yep, that! Someone that reads the warnings :smile:
