### ISSUE TITLE
Tutorial Quest: Steel and your done

### ISSUE THREAD

**Issue by Samji** [Beyond-Reality/Beyond-Reality-Divergence#33]
Coal is provided as the quest reward and is mentioned in the quest info. However a steel works high oven requires charcoal not coal.

**Comment by Dominance** [comment]
It also requires gun powder red stone and sand. I will get it fixed up in the next version leaving this open as a reminder. Thanks for posting keep it coming

**Comment by Samji** [comment]
No problem Dominence I love the pack! (I don't need to build a house and I don't have to grind for the stupid resources - GREAT PACK!!

**Comment by Dominance** [comment]
Fixed up for 1.2.0 should be released soon.
