### ISSUE TITLE
Mod pack will not play in offline mode

### ISSUE THREAD

**Issue by MagasDragouns** [Beyond-Reality/Beyond-Reality-Divergence#333]
I can play it if i am online but not offline.  Where i live i can't get internet so i play offline most of the time. i also have mem. problems soo got it set for 4g and it talking almost all of it just to run and lag bad.  MY PC can play fallout 4 with MAX setting and not lag at all.

**Comment by MagasDragouns** [comment]
oh before you tell me to set jave aug to -XX:+UseG1CG it already set

**Comment by Dominance** [comment]
Not sure why anything would prevent you from playing offline. The only thing I can think of is maybe enviromine try to disable that. That is a long shot but they do have some sort of DRM
oh before you tell me to set jave aug to -XX:+UseG1CG it already set

---

**Comment by MagasDragouns** [comment]
here is the log don't know why it did not show up in the frist post
[Uploading Beyond Reality Divergence log.txt…]()

[Uploading Beyond Reality Divergence log.txt…]()

**Comment by MagasDragouns** [comment]
sorry

**Comment by MagasDragouns** [comment]
ok that did not work . Here is the log AT Launcher has of the problem that I copy paste for you to see if there something that i can do to fix the problem.  
http://www.pasteall.org/69302/javascript
