### ISSUE TITLE
NEI Charcoal (left click & rigth click) crashes the game

### ISSUE THREAD

**Issue by calac64** [Beyond-Reality/Beyond-Reality-Divergence#335]
Every time I click on the charcoal icon in NEI the game crashes. This has happened three times now, I restarted AT Launcher after the first crash and set the texture pack to default after the second. 

Crash reports:
[crash-2016-05-16_18.21.22-client.txt](https://github.com/Beyond-Reality/Beyond-Reality-Divergence/files/267285/crash-2016-05-16_18.21.22-client.txt)
[crash-2016-05-16_20.56.10-client.txt](https://github.com/Beyond-Reality/Beyond-Reality-Divergence/files/267286/crash-2016-05-16_20.56.10-client.txt)
[crash-2016-05-16_21.09.57-client.txt](https://github.com/Beyond-Reality/Beyond-Reality-Divergence/files/267287/crash-2016-05-16_21.09.57-client.txt)

**Comment by Dominance** [comment]
Should be fixed for next version. While this was a binnies related issue it can also happen sometimes in NEI if your INV is full and you attempt to pull items out while in creative.
