### ISSUE TITLE
Forge Version

### ISSUE THREAD

**Issue by Arneal79** [Beyond-Reality/Beyond-Reality-Divergence#336]
Hello,

I play on the only known server that I have found for Divergence.  The owner of the server has had issues updating to the later version of divergence because it runs on an older version of Forge.  Is there any way that you could update the Modpack with the latest Forge so that he can update the server I play on?  Would be greatly appreciated.

Thank You,

Minecraft Username:  Arneal24

**Comment by Dominance** [comment]
Sure thing buddy going to do that in the next version. Should be out tomorrow.
