### ISSUE TITLE
Please for the love of everything holy, I can't load anything!

### ISSUE THREAD

**Issue by calac64** [Beyond-Reality/Beyond-Reality-Divergence#337]
As of recently, I cannot load a new world nor any saves. 

It always freezes (Tested for 2 hours) during a 'menu mob render tick immeadiately after DragonAPO has some error.

[ATLauncher-Log_2016-05-24_00-51-13 txt.txt](https://github.com/Beyond-Reality/Beyond-Reality-Divergence/files/278881/ATLauncher-Log_2016-05-24_00-51-13.txt.txt)

'

**Comment by Buuz135** [comment]
It's not a pack issue, the pack isn't started in the lock, so we can't do anything about it. Try reinstalling the pack.
