### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by essenceoflove** [Beyond-Reality/Beyond-Reality-Divergence#339]
For several days now I can't connect to your website. I get server error! Error 500

**Comment by Dominance** [comment]
Sorry have been in the middle of transferring the old website to beyondrealitygaming.com for a while now. Just got caught up with real life stuff for quite a while now. Also the person whom was paid never finished the job. I haven't had the time to finish it. I will try to restart the old websites server to fix the issue today when I get access to a PC.
On May 30, 2016 10:06 PM, essenceoflove notifications@github.com wrote:For several days now I can't connect to your website. I get server error! Error 500

**Comment by Dominance** [comment]
Website will be moving soon soon will make a announcement when it happens. Should be within the next week.
