### ISSUE TITLE
Homage to the Statues - spelling error

### ISSUE THREAD

**Issue by Samji** [Beyond-Reality/Beyond-Reality-Divergence#34]
"Without there hard work none" - corrected - "Without **_their**_ hard work none"

**Comment by Dominance** [comment]
This is the sign near the temple correct?

**Comment by Samji** [comment]
Within the Temple at the entrance to the room of mod author statues

**Comment by Dominance** [comment]
Having a issue with getting the temple to save again. Moving this to 1.2.1 until I can get it figured out with recurrent complex.

**Comment by Dominance** [comment]
Going to be remaking the temple in future versions to reduce the lag a bit and design the layout to find the quest a bit easier. Closing for now as it will become invalid.
