### ISSUE TITLE
Bee temperatures.

### ISSUE THREAD

**Issue by SkuxxDeluxe** [Beyond-Reality/Beyond-Reality-Divergence#341]
Not sure whats causing it, but
 'taint workin' capt'n!

I have a screenshot of my bees which are normal +/- 1, and they are too hot in a normal environment.

[http://imgur.com/0tjW2cP](url)

**Comment by Diresheep** [comment]
not a bug, is it? Reasonable Realism adds seasons and changing temperatures to biomes. just gotta move biome or wait for the right season

**Comment by Dominance** [comment]
This is caused by seasons inside the pack. Best I can say is there is no real fix other than moving your bees around each season. to new biomes that have their temp changed. So something that may need a plains biome might not work during winter but would in a desert for instance.
