### ISSUE TITLE
Agricraft seeds bypass slow growth

### ISSUE THREAD

**Issue by Rake2244** [Beyond-Reality/Beyond-Reality-Divergence#36]
The potatoes and carrots grown from Agricraft seeds found in the ground will grow exponentially faster than those grown by planting potatoes or carrots themselves.

**Comment by Dominance** [comment]
Indeed something I have noticed myself. If they are disabled from grass drops are you able to attain them otherwise?

**Comment by Rake2244** [comment]
Putting a carrot or potato in the crafting grid gives a seed as well.

**Comment by Dominance** [comment]
kk I got this toned down a bit for 1.2.0 seem to be on par with minecraft stuff now.
