### ISSUE TITLE
Is the modpack dead?

### ISSUE THREAD

**Issue by JFMillerUSA** [Beyond-Reality/Beyond-Reality-Divergence#360]
I noticed the chair in locked rooms just a padlock cube, any chance to finish it like the old modpack. And the plant/flower ore indicators aren't working well to find ores under them. Anyway to unlock Permalocked items?

**Comment by Dominance** [comment]
The manual is a bit outdated which show the old chairs picture and I do not plan on fixing it. So no the old type chairs wont return as it was a crappy model that made the building lag. Indicator flowers do not indicate the ores are directly below. Only within the area. as for the last question.... Why would I go out of my way to permalock something and name it "permalocked" just to have a method to unlock it :)
