### ISSUE TITLE
searching for an item in creative mode is slow

### ISSUE THREAD

**Issue by mvdhoning** [Beyond-Reality/Beyond-Reality-Divergence#38]
Searching for an item in creative mode is slow, it even almost locks up. Not doing logging in atlauncher makes it somewhat better.

**Comment by Dominance** [comment]
Hum yeah no issues here does NEI give you issues as well?

**Comment by mvdhoning** [comment]
NEI seems to be fine in survival mode :-)

**Comment by Dominance** [comment]
Not really sure I know of a way to fix this issue. I guess for now just use creative + :)
