### ISSUE TITLE
Crash when putting Canola seeds into the AgriCraft Seed Analyzer

### ISSUE THREAD

**Issue by Z3r0c00lz** [Beyond-Reality/Beyond-Reality-Divergence#4]
Game Crash when inputting canola into the agricraft seed analyzer after trying to load my world back up after the crash it loads let's me in the world then immediately crashes again rendering the world useless.

<Crash Report>
http://pastebin.com/pcZxC7eq

**Comment by Dominance** [comment]
Classic inter mod compatibility issue. Something like this I will keep open but only attempt to find a solution later on. I am not 100% set in stone with ether agricraft or rotarycraft atm. So at this point most mods can still be cut or some could be added.

**Comment by Dominance** [comment]
With that being said I haven't really tested to force crashes. What I am focused on now is the progression and early game portion of the pack. Tech tree as well.

**Comment by Z3r0c00lz** [comment]
Yeah, I just happened to find a village near the spawn and was going to set up shop there and there was an agricraft green house so I was analyzing all the things and bam no more cool world :P

**Comment by Dominance** [comment]
Good call turned off AgriCraft world gen.
