### ISSUE TITLE
Some metals are too easy to get without mining

### ISSUE THREAD

**Issue by Rake2244** [Beyond-Reality/Beyond-Reality-Divergence#40]
I haven't mined one bit of gold yet and I've gotten a stack and half of ingots.  Each witchery castle usually gives a few pieces of armor, a few ingots, and a partial stack of nuggets.  I'm also sitting on about 9.5 stacks of coins from the Thaumcraft bags.  If you melt down the armor in the smeltery that's a ton of free gold.

I've gotten quite a few minecarts from the new gift bags.  They can be melted in the smeltery for iron and hopper minecarts can be broken down so you can melt the hopper as well.

I've also gotten 2 blocks of steel in bags.

**Comment by Dominance** [comment]
Hum I need to for sure look into a way to disable thaumcrafts loot bags. As for the other loot bags I will look into canning some of the metal items. Thanks for the feedback keep it coming!

**Comment by Dominance** [comment]
Ok for loot bags I have decreased the Iron armor by a great deal. All steel items have been removed. Some Iron items including all types of mine carts as well. Turning off thaumcraft loot bags via tweaker as well. Coming 1.2.0
