### ISSUE TITLE
PgUp and PgDn crashing client

### ISSUE THREAD

**Issue by ptem** [Beyond-Reality/Beyond-Reality-Divergence#41]
As stated in the title, pressing PgUp or PgDn will crash my client to desktop. Have only tested while playing, not in any inventory screens. Currently on 1.1.9.2.

Crash report:
http://pastebin.com/84JS3RCq

**Comment by Dominance** [comment]
Got cha going to get all of these issues sorted by ether tonight or early tomorrow morning EST.

**Comment by Dominance** [comment]
Sent out report to Reika he is normaly very fast and good at getting issues fixed. On another note I have no clue what could be causing this as there is no mod that I know of that would conflict with pg up pg down key binds.

**Comment by Dominance** [comment]
The next version of ChromatiCraft has this fixed. Will implement in next version.
