### ISSUE TITLE
Enabled Aqua Tweaks crash?

### ISSUE THREAD

**Issue by thunderpanter** [Beyond-Reality/Beyond-Reality-Divergence#42]
http://paste.atlauncher.com/view/40714b7d

Received this log when near a village on the Oteg server, after enabling and disabling optional mods it appears that this crash will occur when Aqua Tweaks is enabled. e.g. i had all but Aqua enabled, no problems, enabled aqua both by itself and with the rest, crash.

:cat2:

**Comment by Dominance** [comment]
Very strange your crash issue is ether the same log as the other issues or the other issue is tied to this.
