### ISSUE TITLE
Death caused item dupe spam?

### ISSUE THREAD

**Issue by Rake2244** [Beyond-Reality/Beyond-Reality-Divergence#43]
I was exploring one of the dungeons, where you go past a spawner, then have to go through lava to the other side.  I died in the lava and when I got back to the death point, my fps went down to 0.  I went creative and realized that there was thousands of entities at my death point.  The only items to survive the death were the Tinker's tools, boots, and wings (no dead body was there).  The death point was inside the lava.  The wings were being duplicated by the thousands.  I tried using /cofh killall item 5248 to remove the items but it was only removing a few at a time.  By the time I exited the world there was close to 30k entities at that location.  When I came back in, all the wings were gone.

**Comment by Dominance** [comment]
What wings are you referring to. I think I understand what is happening with the bodies. The only thing that can hurt them besides a player breaking them is lava. I will try to replicate this asap.

**Comment by Rake2244** [comment]
The tinkers construct wings, they let you high jump.

**Comment by Rake2244** [comment]
The odd thing was I couldn't pick up any of the wings.  I was able to pick up my tools, and the tinkers boots I had, but with all the wings on the ground none of them would go in my inventory.

**Comment by Dominance** [comment]
Ok from my testing that dungeon is a little strange. That room where you jump over lava and then have to faceplant into a wall of lava. In that room it is filled with invisible malisis vanishing blocks covered by unbreakable blocks to prevent the player from placing blocks and skipping the hard part of jumping. I could not get it to do it outside of that room.

**Comment by dnangel8042110** [comment]
Let me simplify my experience, if I hold a tinker's tool, pickaxe, for example, when I die not even in a dungeon, there will be a corpse holding my pickaxe. And when I destroy the corpse, there will be thousands of pickaxes on the ground which cause fps drops. And the funny part is there is only one pickaxe real that can be picked up. Others as you can see spinning and doing their fps jobs.

**Comment by Dominance** [comment]
Yeah I have replicated this myself. It would seem as if the cannot be destroyed tinkers tools are conflicting with Lootable bodies. I will get this fixed up

**Comment by Dominance** [comment]
Should be fixed in my testing environment it was at least let me know
