### ISSUE TITLE
Another crash

### ISSUE THREAD

**Issue by thunderpanter** [Beyond-Reality/Beyond-Reality-Divergence#44]
http://paste.atlauncher.com/view/df86d1a3
http://paste.atlauncher.com/view/23f9ce83
noidea why :)

**Comment by Dominance** [comment]
Seems as if your client is out of sync to a server this is SMP correct?

**Comment by thunderpanter** [comment]
Maybe, was just wandering around and it crashed out of the blue :/
yes, it was on the On the edge gamers server if that means anything.

**Comment by Dominance** [comment]
Is this still occurring or was it a one time thing. I have found no way to replicate it.

**Comment by thunderpanter** [comment]
seems it only occured for that day, it nolonger occurs
