### ISSUE TITLE
Road Blocks Chair Bug?

### ISSUE THREAD

**Issue by MystiMayhem** [Beyond-Reality/Beyond-Reality-Divergence#45]
Sitting in the Road Blocks chair doesn't unlock the Road Blocks mod. I've reinstalled and tried it again in a new world with the same results.

**Comment by Dominance** [comment]
Was for sure I had this fixed. Are there doors in your temple?

**Comment by MystiMayhem** [comment]
No, there's HQM Gates.

**Comment by Dominance** [comment]
okie dokie fixed in upcoming 1.2.0 soon to be released.
