### ISSUE TITLE
[Request] Exempt utility animals from expiring

### ISSUE THREAD

**Issue by Githubaccountlol** [Beyond-Reality/Beyond-Reality-Divergence#48]
My friend and I were excited to have found a pair of horses to speed our journeys, until we found they would despawn despite being safe in a fenced pasture and attached to a post via lead.  I assume this is due to the aging mechanics.

This invalidates the usage of pack/saddle animals as your friends are taken by the rapture every couple of hours, leaving behind a broken rope wrapped around a fence, which doesn't even return the lead.

This was actually the first pack I've played where animals were useful, with the lack of early jetpacks/gliders, and saddles being available via loot bags.  Without a way to keep them safe they lose that distinction.

**Comment by Dominance** [comment]
I have reported this issue to @draco18s

**Comment by Draco18s** [comment]
I was sure the aging code recognized animals that were tamed.  I'll have to go look at the code and get back to you.

**Comment by Githubaccountlol** [comment]
Any information one way or the other about designed/intended behavior would be great, no guarantees I've correctly ascertained the root cause of rapture horses!  I believe the behavior matches, but there's all sorts of strange issues with our alternate overworld dimensions on OTE.

I did see that the configs allow for exemptions for aging by class, if nothing else they can be added there.  Thanks guys.

**Comment by Draco18s** [comment]
I was deep in GLSL for most of the day, but I took a look.
Horses aren't part of the Tameable hierarchy, which I would have missed...if I'd actually done anything at all about tame animals! I thought I had, but whoops, I had not (or it got lost somewhere in a code update).

Anyway, its fixed for the next version and the config file change will suffice for now.

**Comment by Githubaccountlol** [comment]
Neato.  Thanks guys.  Is there a way for other things to be exempted?  Perhaps with nametags?  Doesn't matter to me but I am curious how someone would go about having a pet cow or something similar.

**Comment by Draco18s** [comment]
I would have to look into nametags.  Its probably doable, I just have to dig a little deeper.

Thought:
What if name-tagged-entites dropped a nametag on death?

**Comment by Dominance** [comment]
Leaving this open for anyone else experiencing this issue before updating divergence to 1.2.1 but per Reasonable Realism age ignores tamed horses.

**Comment by Draco18s** [comment]
Also wolves and cats.
