### ISSUE TITLE
Silver pressure into uranium

### ISSUE THREAD

**Issue by Dominance** [Beyond-Reality/Beyond-Reality-Divergence#51]
I am not sure how this is happening but on OTE's Server http://i.imgur.com/7hZtV1Q.png in SSP it works as intended http://i.imgur.com/dO1l9OX.png @draco18s

**Comment by Draco18s** [comment]
I actually saw that in the code last night and fixed it >..>

**Comment by Dominance** [comment]
Cool good deal! thanks bro

**Comment by Dominance** [comment]
Thanks again draco fixed it up
