### ISSUE TITLE
Limited Aluminium in the pack?

### ISSUE THREAD

**Issue by damaskinos** [Beyond-Reality/Beyond-Reality-Divergence#52]
Or it's just me? I'm trying to do aluminum brass and I think that I haven't seen any flower of aluminm (the pink ones)

**Comment by helkarakse** [comment]
It appears that these spawn in Mesa biomes or in Swampland.

**Comment by Dominance** [comment]
They can also spawn in rivers by default and I enabled them to spawn in plains as well. The flowers how ever are currently not working. and you may have a harder time locating a cloud

**Comment by Dominance** [comment]
Flowers are working in 1.2.1 Cheers!
