### ISSUE TITLE
JAFF crash with KCauldron

### ISSUE THREAD

**Issue by Towsty** [Beyond-Reality/Beyond-Reality-Divergence#54]
Sorry, the crash was several days ago and I do not have the log still, but this is a server side crash with JAFF and KCauldron 

Crash:
http://paste.ubuntu.com/12406592/

See JAFF forum reference and reply:
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2508671-just-a-few-fish-version-1-0?comment=72

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2508671-just-a-few-fish-version-1-0?comment=76

**Comment by Dominance** [comment]
Yeah its a known issue I talked to him about it a week ago in IRC. Not sure when he plans on getting it fixed up. One of two reasons why its a optional serverside mod. But thank you for posting leaving it open for others,

**Comment by Dominance** [comment]
Not sure what happened to the JAFF dev on fixing this. Closing for now as server owners will just figure it out on there own for the most part if they are using cauldron they are advanced.
