### ISSUE TITLE
1.2.1 wooden rail change has no recipe

### ISSUE THREAD

**Issue by mrbaggins** [Beyond-Reality/Beyond-Reality-Divergence#55]
No recipe comes up when using r or clicking on Wooden track (Railcraft) or wooden rail (Tinkers).

**Comment by Dominance** [comment]
Is this in single player?

**Comment by Dominance** [comment]
Cannot replicate try reinstalling or updating to 1.2.1.1

**Comment by Dominance** [comment]
Yup getting this fixed in a hotfix. Strange that it started acting up outside my dev build

**Comment by mrbaggins** [comment]
Was single, for the record. Which one are we supposed to be using, and is there a recipe that works even if it doesn't show up?

**Comment by Dominance** [comment]
No and Tinkers construct wooden rail + booster track where added without progression with alternate recipes.
