### ISSUE TITLE
Animals using large amounts of server resources 

### ISSUE THREAD

**Issue by cgalliva** [Beyond-Reality/Beyond-Reality-Divergence#60]
Opis screenshots

Individual Entities:
http://imgur.com/yfugTYH

Entities by type:
http://imgur.com/NXJQMil

Tagging @draco18s as well for this issue

When exploring even previously loaded chunks server's tps will drop as low as 5-6 tps. After a restart things are fine mostly but it seems as time goes on there's a steady decline. The decline happens much faster as people load more chunks. 

These screenshots were taken right after a server restart so they don't capture the worst of the performance since opis wasn't installed yet, but I'll add them if I manage to get more later.

**Comment by Draco18s** [comment]
Average: 33μs
You realize that that's 33 _micro_seconds, right?  As in, 33/1000s of a millisecond.  A single game tick is 50,000μs.  The enitre list you have there by type comprises a mere 9,189μs.

Yes, my code is going to consume more CPU time than any vanilla AI task, but it's not severe enough to even be noticeably impacting your server.

**Comment by Dominance** [comment]
The OTE server has also reported slow downs due to the animals @helkarakse may be able to provide further profiles. On a side note would it be possible to add a toggle in the config to disable the animals aging?

**Comment by Draco18s** [comment]
There already is one.
I:GlobalAgeRate=0
Which will do a "is its data valid?" check followed by is an "is it immortal?" lookup, then a "is 0<0?" check, find that false, and exit.

**Comment by Dominance** [comment]
Nice thanks again draco must of missed that in the config!

**Comment by Dominance** [comment]
From my own profiling the config change still produces around the same amount of updates as if it was left on. 2 servers have disabled harderwildlife and have reported a huge decrease on there average load.

**Comment by Draco18s** [comment]
Hmm. :\
I could try dropping an "if GAR==0" check in to either a) not add the AI task at all or b) indicate that it doesn't need to run at all (there's a canRun check that vanilla uses to disable tasks when they aren't valid, e.g. chasing a target when there's no target to chase).
But given all that the task even _does_ when the GAR is 0, I can't imagine that would save a whole lot.

**Comment by Dominance** [comment]
I will be sure to test anything out you send our way!

**Comment by Dominance** [comment]
Should be fixed up in the next release thanks a ton draco!

**Comment by Draco18s** [comment]
Sure thing.
