### ISSUE TITLE
[Suggestion] Teamplay with Nether Keys

### ISSUE THREAD

**Issue by TacoMage** [Beyond-Reality/Beyond-Reality-Divergence#63]
It appears that the usage of the Nether Key is based entirely upon the person who crafts the key and is in no way transferable to other team members (that we could find).  Our suspicion is that it's locked to the achievement you get that is linked to the actual action of crafting the key.  Handing off the key or trying to have another member hold the key while going through the Nether portal does not have any impact on unlocking the dimension.

Is it possible to hook this into the quest system so that it applies to the entire team rather than just the members who craft a key?  With as rare as the keys are, it really feels like it should unlock for the whole team rather than just the one member.

**Comment by Dominance** [comment]
You are correct the quest book is more or less simple documentation that needs to be removed and added to the divergence book. If this was a simple fix I would maybe consider it. Do note that if you are playing in a party you also have more chances to attain that key than a single player would. I myself have played a lot of MMO's as a example that had raids zones locked behind attunement. You as a group made sure everyone was attuned. While as the zone consisted of needing 20+ to progress you could only attune with 5 at a time. I will look into this but if it is not a easy task I wont commit time to fixing something some could refer to as a feature.

**Comment by TacoMage** [comment]
I've seen those kinds of mechanics, and I can't say I've ever cared for them.  They strike me as an arbitrary hurdle to teamplay that seems more centered on increasing average wait-time to do something than making something interesting to play.  But then, I've never been able to get into the larger percentage of MMOs, so it may just be one of those things that doesn't appeal to me as a player.

The part that seems off here is that the key mechanic, taken on its own without a team, is really not that much different than the other bits of progression in Divergence that require the RNG gods to smile upon you.  So you expect it to function like those other things. But, the fact that the progress isn't team-shared highlights that the key mechanic does stand apart from everything else.  The dissonance of these mechanics was surprising since everything in the Overworld is very focused on a "bring a friend" style of play, whereas the keys are "pick your champion and away they go."  The shift is so surprising that it didn't seem intended when we got there.

If the idea actually IS to incentivize a team-split when dealing with dimensions, then the keys are achieving that aim pretty well, since we did that very thing.  If the intent is there, maybe a quick little blurb in the Divergence book about "Kingdoms sending a single well-equipped champion to other dimensions due to keys only allowing a single person to cross over" would at least make the moment when you finally craft a key and learn that only one person can use it a more expected moment.  Or at least a moment that you can look at the book and see that "oh yeah, it's supposed to work like that." As it stands now, as soon as it happened the first thing we said was: "This can't be right, it must be a bug; we should report this."

So, as you say, the simplest solution is to just add it to the Divergence book.  That's pretty much the first thing we look at when anything unexpected happens (like when all our sheep vanished over a few MC days in their pen... woops, sorry, sheep).

**Comment by Dominance** [comment]
So to encourage team play this is my fix. But first the loot bags where added to deal with the smp aspect of the pack. They where not part of the original design. To fix this issue where it is more of a team oriented experience. The temples that contain the key now have multiple keys. Also they spawn every 250 chunks down from every 1500 chunks. The basic token dungeons now spawn every 30 chunks down from every 250 chunks. This is the only fair way I know to do it without writing my own mod that is close to what I am already using to allow for it to unlock upon attaining the key rather than crafting it.  This fix will be available in the next version. You will have to venture out into previously unexplored areas (chunks) to find the new versions of temples that hold multiple keys.

**Comment by TacoMage** [comment]
Sounds like a fair approach.  With the mini-dungeons being relatively more common, I don't think I'd be sad to see the loot bags go away.  Really, I'd rather run a few challenging dungeons than grind at a mob spawner for 30 minutes.  Definitely looking forward to seeing more dungeons to play in.

**Comment by Dominance** [comment]
Got it fixed up next version thanks again for the report keep them coming! will be released soon!
