### ISSUE TITLE
Raw Iron unprocessable with Magneticraft

### ISSUE THREAD

**Issue by helkarakse** [Beyond-Reality/Beyond-Reality-Divergence#64]
Also, as a suggestion, perhaps move the raw iron -> hard ore recipe away from pressure packager into something that requires the use of later game tech?

**Comment by Dominance** [comment]
Well with the pressure packager there is no way to add or remove recipes. I would also have to at that point add a method per mod depending on what tier later game was decided. so for instance with tier 1 that would mean thaumcraft aura cascade chromaticraft witchery hexcraft. That's just on the magic side.

**Comment by helkarakse** [comment]
My mistake, it seems that raw iron is ore-dict'ed with Magneticraft's iron chunk.
