### ISSUE TITLE
Client side Chromaticraft crash

### ISSUE THREAD

**Issue by helkarakse** [Beyond-Reality/Beyond-Reality-Divergence#66]
Crash report: http://pastebin.com/d2NRegk4
Produced by trying to scroll, first with scroll wheel, then with keys (arrow, page up/down) while the chroma lexicon book was open.

**Comment by Dominance** [comment]
I think this may be related to the page up page dn button report. But ether way @ReikaKalseki would be best to determine that.

**Comment by ReikaKalseki** [comment]
It is, and is thus a duplicate (or more correctly, a quadruplicate). Close it.

**Comment by Dominance** [comment]
Thanks bro
