### ISSUE TITLE
Missing textures in Enhanced Inventories is pack specific to BR Divergence

### ISSUE THREAD

**Issue by b0bst3r** [Beyond-Reality/Beyond-Reality-Divergence#70]
I opened this with the mod maker thinking it was just a naming error but apparently it isn't.  Is this something that you can explain Dom?

https://github.com/AnimeniacYuuto/EnhancedInventories/issues/39

**Comment by Dominance** [comment]
Nothing I can explain I will try to look at the FML logs and toss some mods in and out to hopefully figure it out.

**Comment by Dominance** [comment]
Think I have this fixed up in 1.2.2 http://i.imgur.com/AJxXAgl.png Let me know if it is not.
