### ISSUE TITLE
Bypassing Harder Dungeon.

### ISSUE THREAD

**Issue by potop999** [Beyond-Reality/Beyond-Reality-Divergence#76]
Hey,

It's currently possible to bypass the temple structure by breaking the redstone lamps which are normally the exit. You can break them by hand if you know which ones to break.

This makes such a temple easy peasy.

**Comment by Dominance** [comment]
Temple is being redesigned from the ground up. How ever I do not know of any redstone lamps in the main temple. Are you referring to a dungeon?

**Comment by potop999** [comment]
Yeah sorry, I was referring to a dungeon which has a big structure on the top. When you go down, and jump past the lava, you're supposed to go through the pit with the zombie spawner in it and then run through lava and water. But if you look behind you, there are redstone lamps which you can break by hand and get to the reward room without even fighting 1 mob.

**Comment by Dominance** [comment]
Well good find good find! Will be fixing it up next version!
