### ISSUE TITLE
Seared Brick Duplication Glitch

### ISSUE THREAD

**Issue by Bryceclark56** [Beyond-Reality/Beyond-Reality-Divergence#77]
I noticed this while I was playing on OTEGamers.

When you put a seared brick into the smeltery, it makes 144mb.
When you pour out seared stone into an ingot cast, it only costs 32mb or so to produce 1 seared brick.
This means that you can continuously put them back in and never run out; an infinite amount of seared bricks.

**Comment by Dominance** [comment]
Helk fixed it up!
