### ISSUE TITLE
Crash :D

### ISSUE THREAD

**Issue by thunderpanter** [Beyond-Reality/Beyond-Reality-Divergence#78]
http://paste.atlauncher.com/view/f740c86d
Fun fun fun :+1: 
was just exploring in the mining age on the ote server and then i was rip

**Comment by Dominance** [comment]
Ill have @nflantier check it out. I thought for sure this was fixed a couple versions ago.

**Comment by nflantier** [comment]
just found the real issue here :) it was some entities registering problems i will release a fixed versions asap

**Comment by Dominance** [comment]
Thanks nflantier!

**Comment by nflantier** [comment]
the fixed version is up 1.2.3

**Comment by Dominance** [comment]
Thanks again Nflantier will have it patched my side soon!
