### ISSUE TITLE
Some jetpacks added by Simply Jetpacks are not progression-gated

### ISSUE THREAD

**Issue by cesarmalari** [Beyond-Reality/Beyond-Reality-Divergence#79]
Specifically, the Combustion and Kinetic Jetpacks can be created once you have 'Buildcraft' unlocked (for the combustion engine and the stone fluid pipe required in the Combustion Thruster).

**Comment by cesarmalari** [comment]
I should also note that all the jetpacks that _are_ progression-gated need a part that is gated by "Thermal Expansion" (the corresponding flux capacitor) - if it's intended to not gate the combustion/kinetic jetpacks, this unlock should be moved behind "Thermal Expansion".

**Comment by Dominance** [comment]
Id have to look into it It may be something similar to thermal expansion machines. with tag blocks tend to not work to well. Will look into it!
