### ISSUE TITLE
Growthcraft rice paddy

### ISSUE THREAD

**Issue by Gavote** [Beyond-Reality/Beyond-Reality-Divergence#80]
Growthcraft rice paddy cannot be crafted as it requires right clicking farmland with a vanilla shovel. As a result, rice can only be obtained from grass drops.

Edit: and phyto growth

**Comment by mrbaggins** [comment]
Came to post the same issue. Mattock and TC shovels don't work. Can't craft vanilla shovels.

**Comment by Dominance** [comment]
Will be enabling vanilla shovels next version sorry for the delay.

**Comment by Gavote** [comment]
Awesome! Thanks for the quick response! Hmm, maybe just reenable the
diorite shovels so we have a use for it besides decoration?

**Comment by b0bst3r** [comment]
If you don't want to re-enable vanilla tools the diamond tipped shovel from Harder Ores can create rice paddy's.

**Comment by Gavote** [comment]
Aha!

**Comment by b0bst3r** [comment]
Also the Elementium shovel, the Steel (Railcraft) Shovel, Shovel of the purifier (Forbidden Magic), thaumium shovel and the shovel of the earthmover.

**Comment by Dominance** [comment]
Would say this was fixed but yeah I forgot to disable them not being usable. Diamond tip for now.

**Comment by Dominance** [comment]
Fixed in upcoming version https://github.com/Beyond-Reality/Beyond-Reality-Divergence/commit/8f56a5ace4a62c4c2eda44136a589cd6bc9baf6e
