### ISSUE TITLE
Unable to Make Other kinds of Jerky

### ISSUE THREAD

**Issue by ghost** [Beyond-Reality/Beyond-Reality-Divergence#81]
Players have reported that they are unable to make other kinds of Jerky besides monster because of the subdata that rotten has on the food. I can inquire about it more from players if needed.

**Comment by Dominance** [comment]
I am not sure it is possible to blacklist items from rotting. I looked into it briefly but found nothing that lead to it. I will check again or if anyone else knows of a method let me know!

**Comment by Dominance** [comment]
Wont be able to fix this how ever I did find a way to turn off spider eyes, Fermented Spider Eyes, Slimballs and rotten flesh from spoiling.
