### ISSUE TITLE
Creosote and coke ovens incompatibility

### ISSUE THREAD

**Issue by mrbaggins** [Beyond-Reality/Beyond-Reality-Divergence#84]
Making a Railcraft Coke oven, when used creates Immersive engineering creosote, which is incompatible with all the railcraft item crafting. Needs either a conversion method, or fluid-forge dictionary matching, or tweaked recipes to allow both for either.

**Comment by ghost** [comment]
In my mod pack I just made a quick minetweaker recipe that made them interchangeable so you could swap them around to the one you needed. Thats how I solved it just an idea.

**Comment by Dominance** [comment]
It is also how I originally solved this issue how ever there was another issue that pops up using that method.

**Comment by mrbaggins** [comment]
Should this be closed? As it stands I think the only way to make rail ties is with a carpenter.

**Comment by Dominance** [comment]
Have to click on the commit to see the changes. Next version it will be fixed which is coming soon.

 Dominance closed this in --------->  6ccc217  <---------   an hour ago

**Comment by mrbaggins** [comment]
Ah sorry, was on mobile and the commit SHA wasn't there. Just had a closed message.
