### ISSUE TITLE
Fired clay buckets remove oil source block but don't actually pick the oil up.

### ISSUE THREAD

**Issue by b0bst3r** [Beyond-Reality/Beyond-Reality-Divergence#85]
Also along the same lines, when you pick up BC oil in an iron bucket it turns into a magneticraft oil bucket, when you put this into a BC combustion engine it consumes the bucket (both ways).

Both ways being right clicking engine with oil bucket in hand (consumes bucket) or by placing oil bucket in GUI (consumes bucket).

**Comment by Dominance** [comment]
May just dump the buckets from the game. Dont think there is a way to fix it on my end and they are not really needed in a pack like this compared to something like a gregtech pack where they would be golden. I will look into it how ever.

**Comment by b0bst3r** [comment]
Those clay buckets are in the mob loot bags.

Also I put 2 issues into 1, just wanted to make sure you noticed the 2nd :)

**Comment by Dominance** [comment]
Yeah I seen it. Going to see if I can just disable the Magneticraft oilbucket
