### ISSUE TITLE
Carpenters block not accepting input

### ISSUE THREAD

**Issue by thunderpanter** [Beyond-Reality/Beyond-Reality-Divergence#88]
As the title says, on the ote server i can place,craft the carpenters blocks, i have unlocked the mod and sat in the chair etc. However, if i for example want some stone stairs, it doest accept the stone block, and places it on the floor. 

I have been able to do this on single player successfully, but no matter what block I use, it doesn't allow it. People have been able to use them without issue before.

**Comment by Dominance** [comment]
So this works on single player but not on a server?

**Comment by thunderpanter** [comment]
yeah, no change on the new update either.

**Comment by Dominance** [comment]
Yeah I am going to look into fixing this and replicating it. Just pushed thoughts last fixes as they where already on the burner.
