### ISSUE TITLE
Few things

### ISSUE THREAD

**Issue by ghost** [Beyond-Reality/Beyond-Reality-Divergence#89]
I have found a few things I wanted to address. The first one is the captcha on your website for registering does not work. It shows a broken image. The second thing is the camelpack it won't let me put water in it unless I am doing something wrong. I try putting the camel pack in a crafting table with water bottles and nothing happens. How am I supposed to fill it? Also the quest where you turn in cobble stone in the beginning it says any cobble stone. If you get cobble stone from a village building it won't let you turn that in. And I am not sure how big an ore vein is supposed to be but I filled up to double chests with iron and I still haven't found the end of the vein. If that is normal then never mind :)

**Comment by mrbaggins** [comment]
Camel pack working fine for me.

Not sure on village cobble, haven't found one yet.

Yes, ore veins are huge. Remember where it is, it might be the only iron you find for a fair while.

**Comment by Dominance** [comment]
The camel pack does have a visual glitch. If you craft it with water in a crafting table it will sometimes now visually show up with a output. It is there but for some reason you cannot see it. Just click and drag it from the output box as normal and you will get it filled. I never considered villager cobblestone and thought I had it set as ore dictionary in the book. Will fix it up.

**Comment by ghost** [comment]
Also another one I forgot to mention. So I had the big structure spawn in middle of a village and part of the village was inside the structure. It broke a wall so I could get into a few rooms before I unlocked it if I had wanted. That was an old world I restarted my world because of it. Not sure if that is something that can be fixed or not.

**Comment by ghost** [comment]
Also the camel pack worked like a charm thank you for that. Might want to put a note in the HQM book though when you get it. Just an idea.

**Comment by ghost** [comment]
Also what about the captcha? I would like to be able to register :P

**Comment by Dominance** [comment]
Captcha I will look into it first thing in the morning. World Generation that breaks the temple such as village walls/AE2 meteors or a elephant traped inside during temple generation. I cannot fix Just have to remake and get a new seed.

**Comment by ghost** [comment]
OK I had figured but I wasn't sure about it.

**Comment by Dominance** [comment]
Captcha is gone @Aknotsdeath your good to sign up sorry for the delay. Thanks for the heads up keep on keeping on sending in issues.
