### ISSUE TITLE
Issue with Tinkers Basic chair

### ISSUE THREAD

**Issue by lilmoefow** [Beyond-Reality/Beyond-Reality-Divergence#9]
In the first Tinker Construct room, when clicking on the Tinkers Basic chair you get stuck on it as if you are mounting a horse or sitting in a minecart.  You are still able to walk away from it as if nothing has changed, and you wont notice anything is wrong till you try to break blocks.  Just hit shift to "demount" the chair and everything will be fine.

**Comment by Dominance** [comment]
All chair issues fixed in 1.0.8 :)
