### ISSUE TITLE
Pre-existing dungeons from before the update still cause a crash

### ISSUE THREAD

**Issue by thunderpanter** [Beyond-Reality/Beyond-Reality-Divergence#92]
http://paste.atlauncher.com/view/1e1447ac
Took a walk past a dungeon that has been loaded from ages ago, got crashed :c
New chunk dungeons working as intended

**Comment by thunderpanter** [comment]
It also appears that after being moved to spawn, the crash still persists.

**Comment by Dominance** [comment]
Yeah as stated in the change log nothing I can do about pre-existing ones. But the new ones are fixed :)
