### ISSUE TITLE
No way to convert Unstable stone --> Stone

### ISSUE THREAD

**Issue by thunderpanter** [Beyond-Reality/Beyond-Reality-Divergence#94]
No way to convert Unstable stone --> Stone, but you can convert Unstable cobblestone --> cobblestone, you can also use chisel to bypass the recipe and just straight up change unstable cobblestone into cobblestone.

**Comment by mrbaggins** [comment]
Yeah, a recipe for unstable stone -> stone would be good. Just made a bunch trying to make roads, and it's useless.

**Comment by b0bst3r** [comment]
Why not just furnace the cobble into stone once you changed it into normal cobblestone with chisel?  Or you can craft it into slabs then back into normal cobble without chisel.  Can't shortcut everything :p

**Comment by Dominance** [comment]
Yes the only method is to craft cobble with two cobble two sticks to make default cobblestone and then furnace it much like you normally would. Or unlock chisel and convert it with the tool.
