### ISSUE TITLE
No aluminium?

### ISSUE THREAD

**Issue by mrbaggins** [Beyond-Reality/Beyond-Reality-Divergence#95]
Been struggling to find aluminium in the world. Found some sparse stuff, which was enough to make my first casts, and I've been using gold since. So I checked the website chart, which doesn't even list aluminium?

And then looking at the configs, it's not in Cofh-world either...

Oversight, or am I missing something?

**Comment by cesarmalari** [comment]
You're looking for Bauxite, and it's generated via COG.

This is the chunk of the COG configs that generate it: https://github.com/Beyond-Reality/Beyond-Reality-Divergence/blob/master/config/CustomOreGen/modules/custom/HarderExtraOres.xml#L1263  It should now be a standard-style vein + motherlode setup, just below the surface (average Y level: 58).  Look for the flowers and hardened clay in places where it doesn't belong. (at least, I think flowers are working now, aren't they @Dominance?)

note: if you're on a server whose world was generated with earlier configs (ie. before https://github.com/Beyond-Reality/Beyond-Reality-Divergence/commit/1d3f876807e582bc48e9a7db702a375eb90481a4 was applied), Bauxite is in clouds just below the surface, not vein + motherlode

**Comment by mrbaggins** [comment]
Ah okay, half my world is before that, half after. I'll keep looking for flowers. What flowers is it? The aluminium one is apparently a pink one, can't remember if there was a bauxite one.

**Comment by cesarmalari** [comment]
Hmm... apparently the ore is only referred to as Bauxite internally - all the blocks are actually called Aluminum...  Guess we need to update that chart :(

As for the flowers, yes, it should be Affine.

**Comment by b0bst3r** [comment]
Chart is not correct anyway, I've been finding diamond clumps of hard ore around Y35-37 chart says it's at bedrock.

**Comment by Dominance** [comment]
I will be doing a much grander chart for the site that shows the shapes of the veins and such along side the charts. Closing this for now as it is invalid.
